/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Navarro
 */
public class frmAjustes extends javax.swing.JFrame {


    DefaultTableModel model;
    private String hora;

    public frmAjustes() {
        this.setlook();
        initComponents();
        setLocationRelativeTo(null);
    }
    

    public void setTitle(String title) {
        super.setTitle(title);
    }

    public void setlook() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void restaurarVentana() {
        if (getExtendedState() == JFrame.MAXIMIZED_BOTH) {//1
            setExtendedState(JFrame.NORMAL);//2
        } else {
            setExtendedState(JFrame.MAXIMIZED_BOTH);//3
        }
    }

    /*public void LlenarVariables() {
        try {
            String sql = "select * from variables where codvar = '1'";
            ResultSet rs = acciones.Consultar(sql);
            while (rs.next()) {
                txtIva.setText(rs.getString("iva"));
                txtRuta.setText(rs.getString("ruta"));
                txtHora.setText(rs.getString("hora"));
            }
            acciones.conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }*/
    
       public void Ajustar(JLabel label, ImageIcon icon) {
        //esta funcion ajusta un icono(parametro) al tamaño del label (parametro)
        Icon icono = new ImageIcon(icon.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_DEFAULT));
        label.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        lblTitulo3 = new javax.swing.JLabel();
        txtRuta = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        btnSalir2 = new javax.swing.JButton();
        txtIva = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        lblTitulo4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnBuscar1 = new javax.swing.JButton();
        btnBuscar2 = new javax.swing.JButton();
        lblTitulo16 = new javax.swing.JLabel();
        lblTitulo17 = new javax.swing.JLabel();
        lblTitulo18 = new javax.swing.JLabel();
        btnBuscar4 = new javax.swing.JButton();
        txtHora1 = new javax.swing.JTextField();
        txtHora2 = new javax.swing.JTextField();
        btnBuscar5 = new javax.swing.JButton();
        btnBuscar6 = new javax.swing.JButton();
        btnBuscar7 = new javax.swing.JButton();
        btnBuscar8 = new javax.swing.JButton();
        lblTitulo15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Variables del Sistema");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(1, 87, 155));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(69, 90, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTitulo1.setText("Limite de Alumos por seccion");
        jPanel1.add(lblTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 180, 20));

        lblTitulo2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitulo2.setText("%");
        jPanel1.add(lblTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 20, 20));

        lblTitulo3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTitulo3.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo3.setText("Ubicacion de Reportes ");
        jPanel1.add(lblTitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 150, 20));

        txtRuta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtRuta.setEnabled(false);
        jPanel1.add(txtRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 350, -1));

        txtUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtUsuario.setEnabled(false);
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 110, -1));

        btnSalir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PImagenes/agt_action_fail.png"))); // NOI18N
        btnSalir2.setText("Salir");
        btnSalir2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 100, 30));

        txtIva.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIva.setEnabled(false);
        txtIva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIvaKeyTyped(evt);
            }
        });
        jPanel1.add(txtIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 80, -1));

        txtHora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtHora.setEnabled(false);
        jPanel1.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 100, -1));

        lblTitulo4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTitulo4.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitulo4.setText("Valor Actual Iva");
        jPanel1.add(lblTitulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 140, 20));

        jButton2.setText("...");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 30, -1));

        btnBuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PImagenes/1497913416_gtk-refresh.png"))); // NOI18N
        btnBuscar1.setContentAreaFilled(false);
        btnBuscar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 30, 20));

        btnBuscar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PImagenes/agt_family.png"))); // NOI18N
        btnBuscar2.setContentAreaFilled(false);
        btnBuscar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 30, 20));

        lblTitulo16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTitulo16.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitulo16.setText("Dias para mora");
        jPanel1.add(lblTitulo16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 130, 20));

        lblTitulo17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTitulo17.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitulo17.setText("Precio Cuota Mensual");
        jPanel1.add(lblTitulo17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, 20));

        lblTitulo18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTitulo18.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitulo18.setText("Precio de Mora");
        jPanel1.add(lblTitulo18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 130, 20));

        btnBuscar4.setText("Actualizar");
        btnBuscar4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 90, 20));

        txtHora1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtHora1.setEnabled(false);
        jPanel1.add(txtHora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 100, -1));

        txtHora2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtHora2.setEnabled(false);
        jPanel1.add(txtHora2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 100, -1));

        btnBuscar5.setText("Actualizar");
        btnBuscar5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar5ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 90, 20));

        btnBuscar6.setText("Actualizar");
        btnBuscar6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar6ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 90, 20));

        btnBuscar7.setText("Actualizar");
        btnBuscar7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar7ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 90, 20));

        btnBuscar8.setText("Actualizar");
        btnBuscar8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar8ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 90, 20));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 565, 250));

        lblTitulo15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTitulo15.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitulo15.setText("Ajustes");
        jPanel3.add(lblTitulo15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 280, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed

    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged

    }//GEN-LAST:event_jPanel3MouseDragged

    private void btnSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir2ActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalir2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
/*   JFileChooser explorador = new JFileChooser("\\home\\");
    explorador.setDialogTitle("Abrir ubicacion de los reportes...");
    explorador.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    int seleccion = explorador.showDialog(null, "Abrir!");
    //Podemos crear un File con lo seleccionado
    File archivo = explorador.getSelectedFile();

    //y guardar una ruta
    String ruta = archivo.getPath();
    //analizamos la respuesta
    switch(seleccion) {
    case JFileChooser.APPROVE_OPTION:
        try {
                String sql = "update variables set ruta=?";
                PreparedStatement ps = acciones.Actualizar(sql);
                ps.setString(1, ruta);    
                int n = ps.executeUpdate();
                if (n > 0) {
                    txtRuta.setText(ruta);
                    JOptionPane.showMessageDialog(null, "Ruta Actualizada con exito",
                            "Informacion", JOptionPane.PLAIN_MESSAGE, iconCorrecto);
                    acciones.conn.close();
                }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error al Actualizar Ruta\ncodigo error:" + e.getMessage(),
                        "Error", JOptionPane.PLAIN_MESSAGE, iconError);
                }
     break;

    case JFileChooser.CANCEL_OPTION:
     //dio click en cancelar o cerro la ventana
     break;

    case JFileChooser.ERROR_OPTION:
     //llega aqui si sucede un error
     break;
    }*/
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtIvaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIvaKeyTyped

    }//GEN-LAST:event_txtIvaKeyTyped

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed

    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void btnBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar2ActionPerformed

    }//GEN-LAST:event_btnBuscar2ActionPerformed

    private void btnBuscar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscar4ActionPerformed

    private void btnBuscar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscar5ActionPerformed

    private void btnBuscar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscar6ActionPerformed

    private void btnBuscar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscar7ActionPerformed

    private void btnBuscar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscar8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAjustes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnBuscar2;
    private javax.swing.JButton btnBuscar4;
    private javax.swing.JButton btnBuscar5;
    private javax.swing.JButton btnBuscar6;
    private javax.swing.JButton btnBuscar7;
    private javax.swing.JButton btnBuscar8;
    private javax.swing.JButton btnSalir2;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo15;
    private javax.swing.JLabel lblTitulo16;
    private javax.swing.JLabel lblTitulo17;
    private javax.swing.JLabel lblTitulo18;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JLabel lblTitulo4;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtHora1;
    private javax.swing.JTextField txtHora2;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtRuta;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

   /* private void LlenarTabla() {
        try {
            String[] titulos = {"Codigo", "Categoria"};
            String sql = "select * from tipoproducto";
            model = new DefaultTableModel(null, titulos);
            ResultSet rs = acciones.Consultar(sql);
            String[] fila = new String[8];
            while (rs.next()) {
                fila[0] = rs.getString("codtip");
                fila[1] = rs.getString("tipprod");
                model.addRow(fila);
            }
            tbl.setModel(model);
            acciones.conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    private boolean EventoKeyType(int valor, int limitacion){
            //pido el valor del text y pido el valor limitante
            if (valor >= limitacion) {
                return true;
            }else{
                return false;
            }
    }

    private boolean Verificacion(String cadena) {
        boolean tipo = true;
        try {
            String sql = "select * from tipoproducto where tipprod = '"+cadena+"'";
            ResultSet rs = acciones.Consultar(sql);
            while (rs.next()) {
                JOptionPane.showMessageDialog(null, "Categoria ya Existe",
                        "Advertencia", JOptionPane.PLAIN_MESSAGE, iconAd);
                tipo = false;
            }
            acciones.conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return tipo;
    }*/
}
