/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Coordinador;
import VO.AlumnoVO;
import VO.RepresentanteVO;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class frmGrupos extends javax.swing.JFrame {

    private Coordinador coordinador;
        private final ImageIcon ICON_NO_PHOTO = new javax.swing.ImageIcon(getClass().getResource("/Recursos/no_photo2.png"));
         private final ImageIcon iconLogo = new javax.swing.ImageIcon(getClass().getResource("/Recursos/logo.png"));
    FileInputStream fis, fis1, fis2, fis3, fisCopia1, fisCopia2;
    int longitudBytes, longitudBytes1,longitudBytes2,longitudBytes3, longitudBytecopia1, longitudBytecopia2;

    /**
     * Creates new form frmGrupos
     */
    public frmGrupos() {
        this.setlook();
        initComponents();
        ajustar(lblLogo, iconLogo);
    }
    
     public void setlook() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void ajustar(JLabel label, ImageIcon icon) {
        //esta funcion ajusta un icono(parametro) al tamaño del label (parametro)
        Icon icono = new ImageIcon(icon.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_DEFAULT));
        label.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSeccion = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMatricula = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        btnAtras = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbxSeccion = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnLlenar = new javax.swing.JButton();
        lblUsuarioActvo = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSeccion1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        btnAtras2 = new javax.swing.JButton();
        btnGuardar2 = new javax.swing.JButton();
        cbxSeccion1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        lblUsuarioActvo2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbxSeccion2 = new javax.swing.JComboBox<>();
        jScrollPane11 = new javax.swing.JScrollPane();
        tblSeccion2 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        lblLogo = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N

        jTabbedPane3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(1, 87, 155));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Grupos");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 730, -1));

        tblSeccion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblSeccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Primer Nombre", "Primer Apellido"
            }
        ));
        tblSeccion.setName("tblSeccion"); // NOI18N
        tblSeccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSeccionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSeccion);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 390, 310));

        tblMatricula.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblMatricula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblMatricula.setName("tblMatricula"); // NOI18N
        tblMatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMatriculaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMatricula);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 290, 310));

        btnAtras.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icon_exit24.png"))); // NOI18N
        btnAtras.setText("Salir");
        btnAtras.setName("btnAtras"); // NOI18N
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel2.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 100, -1));

        btnGuardar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icon_guardar24.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setName("btnGuardar"); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Matricula");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        cbxSeccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maternal", "I", "II", "III" }));
        cbxSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSeccionActionPerformed(evt);
            }
        });
        jPanel2.add(cbxSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 110, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Grupo a cargar");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 140, -1));

        btnLlenar.setText("Actualizar Tabla");
        btnLlenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlenarActionPerformed(evt);
            }
        });
        jPanel2.add(btnLlenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 190, -1));

        lblUsuarioActvo.setText("usuario activo");
        lblUsuarioActvo.setName("lblUsuarioActivo"); // NOI18N
        jPanel2.add(lblUsuarioActvo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 120, 20));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/carpeta.png"))); // NOI18N
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/contratado(1).png"))); // NOI18N
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        jTabbedPane3.addTab("AGREGAR ALUMNO", new javax.swing.ImageIcon(getClass().getResource("/Recursos/icon_graduado.png")), jPanel2); // NOI18N

        jPanel7.setBackground(new java.awt.Color(1, 87, 155));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cambiar alumno de grupo");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 730, 40));

        tblSeccion1.setBackground(new java.awt.Color(69, 90, 100));
        tblSeccion1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Primer Nombre", "Primer Apellido"
            }
        ));
        tblSeccion1.setEnabled(false);
        tblSeccion1.setName("tblSeccion"); // NOI18N
        tblSeccion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSeccion1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblSeccion1);

        jPanel7.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 370, 310));

        btnAtras2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnAtras2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icon_exit24.png"))); // NOI18N
        btnAtras2.setText("Salir");
        btnAtras2.setName("btnAtras"); // NOI18N
        btnAtras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtras2ActionPerformed(evt);
            }
        });
        jPanel7.add(btnAtras2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 100, -1));

        btnGuardar2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnGuardar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icon_guardar24.png"))); // NOI18N
        btnGuardar2.setText("Guardar");
        btnGuardar2.setName("btnGuardar"); // NOI18N
        btnGuardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar2ActionPerformed(evt);
            }
        });
        jPanel7.add(btnGuardar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, -1, -1));

        cbxSeccion1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        cbxSeccion1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        cbxSeccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSeccion1ActionPerformed(evt);
            }
        });
        jPanel7.add(cbxSeccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 110, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Grupo a cambiar");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, 160, -1));

        lblUsuarioActvo2.setText("usuario activo");
        lblUsuarioActvo2.setName("lblUsuarioActivo"); // NOI18N
        jPanel7.add(lblUsuarioActvo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 120, 20));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Grupo Actual");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 140, -1));

        cbxSeccion2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        cbxSeccion2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        cbxSeccion2.setSelectedIndex(1);
        cbxSeccion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSeccion2ActionPerformed(evt);
            }
        });
        jPanel7.add(cbxSeccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 110, -1));

        tblSeccion2.setBackground(new java.awt.Color(69, 90, 100));
        tblSeccion2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Primer Nombre", "Primer Apellido"
            }
        ));
        tblSeccion2.setEnabled(false);
        tblSeccion2.setName("tblSeccion"); // NOI18N
        tblSeccion2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSeccion2MouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(tblSeccion2);

        jPanel7.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 370, 310));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logo.png"))); // NOI18N
        jPanel7.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 120, 120));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/grupo(1).png"))); // NOI18N
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/contratado(1).png"))); // NOI18N
        jPanel7.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, -1, -1));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/exchange-arrows(2).png"))); // NOI18N
        jPanel7.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 130, 110));

        jTabbedPane3.addTab("CAMBIAR ALUMNO", new javax.swing.ImageIcon(getClass().getResource("/Recursos/icon_user.png")), jPanel7); // NOI18N

        jTabbedPane1.addTab("GRUPOS", jTabbedPane3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLlenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlenarActionPerformed
       tblMatricula.setModel(coordinador.consultarMatriculaSinSeccion()); 
    }//GEN-LAST:event_btnLlenarActionPerformed

    private void tblMatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMatriculaMouseClicked
        if (evt.getClickCount() == 2) {
            int cantidadenBD = coordinador.consultarCantidadDeAlumnoSeccion(cbxSeccion.getSelectedItem().toString());
            int limite = coordinador.getVariablesDAO().consultarVariables().getLimite_alumno();
            int cantidadTabla = tblSeccion.getRowCount();
            if (cantidadenBD < limite) {
                if (cantidadTabla < limite) {
                    DefaultTableModel model = null;
                    int fila = this.tblMatricula.getSelectedRow();
                    model = (DefaultTableModel) tblMatricula.getModel();
                    tblSeccion.setModel(coordinador.añadirListaGrupos(tblMatricula, tblSeccion, fila));
                    model.removeRow(fila);
                    tblMatricula.setModel(model);
                } else {
                    coordinador.getLogica().mensajeError("La seccion ha llegado al limite de alumnos por favor seleccione otra seccion");
                } 
            } else {
                coordinador.getLogica().mensajeError("La seccion ha llegado al limite de alumnos por favor seleccione otra seccion");
            }
        }
    }//GEN-LAST:event_tblMatriculaMouseClicked

    private void tblSeccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSeccionMouseClicked

    }//GEN-LAST:event_tblSeccionMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
           if (tblSeccion.getRowCount() >0) {
            DefaultTableModel model = (DefaultTableModel) tblSeccion.getModel();
            String respuesta= "";
            int id_alumno = 0;
            for (int i = 0; i < tblSeccion.getRowCount(); i++) {
                VO.MatriculaVO matriculaVO = new VO.MatriculaVO();
                matriculaVO.setId_alumno(model.getValueAt(i, 0).toString());
                matriculaVO.setSeccion(cbxSeccion.getSelectedItem().toString());
                respuesta = coordinador.getMatriculaDAO().actualizarMatricula(matriculaVO, String.valueOf(matriculaVO.getId_alumno()));
            }
           if (respuesta.equals("UPDATE")) {
                    coordinador.getLogica().mensajeCorrecto("Datos Actualizados con exito");
                }else{
                     coordinador.getLogica().mensajeError("Error al guardar datos");
                }
            coordinador.borrarTablas(tblSeccion, tblMatricula);
            tblMatricula.setModel(coordinador.consultarMatriculaSinSeccion()); 
        } else {
            coordinador.getLogica().mensajeAdvertencia("Consulte un seccion");
        }    
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
      coordinador.getFrmMenu().setVisible(true);
      coordinador.getFrmMenu().setLocationRelativeTo(null);
      this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void cbxSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSeccionActionPerformed
        tblSeccion.setModel(coordinador.consultarMatriculaPorSeccionTabla(cbxSeccion.getSelectedItem().toString()));
    }//GEN-LAST:event_cbxSeccionActionPerformed

    private void tblSeccion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSeccion1MouseClicked
        if (evt.getClickCount() == 2 && tblSeccion2.isEnabled()) {
            int cantidadenBD = coordinador.consultarCantidadDeAlumnoSeccion(cbxSeccion2.getSelectedItem().toString());
            int limite = coordinador.getVariablesDAO().consultarVariables().getLimite_alumno();
            int cantidadTabla = tblSeccion2.getRowCount();
           if (cantidadenBD < limite) {
                if (cantidadTabla < limite) {
            int fila = this.tblSeccion1.getSelectedRow();
            tblMatricula.setModel(coordinador.añadirListaAsistentes(tblSeccion1, tblSeccion2, fila));
            DefaultTableModel model = (DefaultTableModel) tblSeccion1.getModel();
            model.removeRow(fila);
            tblSeccion1.setModel(model);
                                } else {
                                coordinador.getLogica().mensajeError("La seccion ha llegado al limite de alumnos por favor seleccione otra seccion");
                } 
            } else {
                 coordinador.getLogica().mensajeError("La seccion ha llegado al limite de alumnos por favor seleccione otra seccion");
                
            }
        }
    }//GEN-LAST:event_tblSeccion1MouseClicked

    private void btnAtras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtras2ActionPerformed
    this.dispose();
    }//GEN-LAST:event_btnAtras2ActionPerformed

    private void btnGuardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar2ActionPerformed
        if (tblSeccion2.getRowCount() >0) {
            DefaultTableModel model = (DefaultTableModel) tblSeccion2.getModel();
            String respuesta= "";
            int id_alumno = 0;
            for (int i = 0; i < tblSeccion2.getRowCount(); i++) {
                VO.MatriculaVO matriculaVO = new VO.MatriculaVO();
                matriculaVO.setId_alumno(model.getValueAt(i, 0).toString());
                matriculaVO.setSeccion(cbxSeccion2.getSelectedItem().toString());
                respuesta = coordinador.getMatriculaDAO().actualizarMatricula(matriculaVO, String.valueOf(matriculaVO.getId_alumno()));
            }
           if (respuesta.equals("UPDATE")) {
                    coordinador.getLogica().mensajeCorrecto("Datos Actualizados con exito");
                }else{
                     coordinador.getLogica().mensajeError("Error al guardar datos");
                }
            coordinador.borrarTablas(tblSeccion2, tblSeccion1);
            tblSeccion1.setModel(coordinador.consultarMatriculaPorSeccionTabla(cbxSeccion1.getSelectedItem().toString()));
            tblSeccion2.setModel(coordinador.consultarMatriculaPorSeccionTabla(cbxSeccion2.getSelectedItem().toString()));
        } else {
           coordinador.getLogica().mensajeError("Consulte una seccion");
        }  
    }//GEN-LAST:event_btnGuardar2ActionPerformed

    private void cbxSeccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSeccion1ActionPerformed
        if (cbxSeccion1.getSelectedIndex()==cbxSeccion2.getSelectedIndex()) {
            coordinador.getLogica().mensajeError("No se Puede seleccionar la misma seccion");
            tblSeccion1.setEnabled(false);
        }else{
             tblSeccion1.setModel(coordinador.consultarMatriculaPorSeccionTabla(cbxSeccion1.getSelectedItem().toString()));
             tblSeccion1.setEnabled(true);
        }
    }//GEN-LAST:event_cbxSeccion1ActionPerformed

    private void cbxSeccion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSeccion2ActionPerformed
        if (cbxSeccion2.getSelectedIndex()==cbxSeccion1.getSelectedIndex()) {
            coordinador.getLogica().mensajeError("No se Puede seleccionar la misma seccion");
            tblSeccion2.setEnabled(false);
        }else{
            tblSeccion2.setModel(coordinador.consultarMatriculaPorSeccionTabla(cbxSeccion2.getSelectedItem().toString()));
            tblSeccion2.setEnabled(true);
        }
    }//GEN-LAST:event_cbxSeccion2ActionPerformed

    private void tblSeccion2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSeccion2MouseClicked
    if (evt.getClickCount() == 2 && tblSeccion1.isEnabled()) {
            int fila = this.tblSeccion2.getSelectedRow();
            tblMatricula.setModel(coordinador.añadirListaAsistentes(tblSeccion2, tblSeccion1, fila));
            DefaultTableModel model = (DefaultTableModel) tblSeccion2.getModel();
            model.removeRow(fila);
            tblSeccion2.setModel(model);
        }
    }//GEN-LAST:event_tblSeccion2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGrupos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnAtras2;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardar2;
    private javax.swing.JButton btnLlenar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cbxSeccion;
    private javax.swing.JComboBox<String> cbxSeccion1;
    private javax.swing.JComboBox<String> cbxSeccion2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel lblLogo;
    public javax.swing.JLabel lblUsuarioActvo;
    public javax.swing.JLabel lblUsuarioActvo2;
    private javax.swing.JTable tblMatricula;
    public javax.swing.JTable tblSeccion;
    public javax.swing.JTable tblSeccion1;
    public javax.swing.JTable tblSeccion2;
    // End of variables declaration//GEN-END:variables

    public void setCoordinador(Coordinador coordinador) {
       this.coordinador = coordinador;
    }

    private void validacionSoloLetras(KeyEvent evt, int maximo, int lim) {
        if (coordinador.validacionSoloLetras(evt.getKeyChar() + "")) {
            if (lim >= maximo) {
                evt.consume();
                getToolkit().beep();
            }
        } else {
            evt.consume();
            getToolkit().beep();
        }
    }
    
    private void validacionSoloLetrasEspacio(KeyEvent evt, int maximo, int lim) {
        if (coordinador.validacionSoloLetrasEspacio(evt.getKeyChar() + "")) {
            if (lim >= maximo) {
                evt.consume();
                getToolkit().beep();
            }
        } else {
            evt.consume();
            getToolkit().beep();
        }
    }

    private void validacionLimite(KeyEvent evt, int maximo, int lim) {
        if (lim >= maximo) {
            evt.consume();
            getToolkit().beep();
        }
    }

    private void validacionTelefono(KeyEvent evt, int maximo, int lim) {
        if (coordinador.validacionLimiteSoloNumerosYGuion(evt.getKeyChar() + "")) {
            if (lim >= maximo) {
                evt.consume();
                getToolkit().beep();
            }
        } else {
            evt.consume();
            getToolkit().beep();
        }
    }

    private void validacionSoloNumeros(KeyEvent evt, int maximo, int lim) {
        if (coordinador.validacionLimiteSoloNumeros(evt.getKeyChar() + "")) {
            if (lim >= maximo) {
                evt.consume();
                getToolkit().beep();
            }
        } else {
            evt.consume();
            getToolkit().beep();
        }
    }

    private boolean registrarMatricula() {
        VO.MatriculaVO matriculaVO = new VO.MatriculaVO();
        //matriculaVO.setId_alumno(Integer.parseInt(lblCodigo.getText()));
        matriculaVO.setId_empleado(coordinador.consultarUsuario(lblUsuarioActvo.getText()).getId_usuario());
        if (coordinador.registrarMatricula(matriculaVO).equals("INGRESADO CON EXITO")) {
            return true;
        } else {
            return false;
        }
    }

}
