/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Lenovo
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblHora = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        btnAjustes = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        lblNota = new javax.swing.JLabel();
        lblInscripcion = new javax.swing.JLabel();
        lblPago = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblAsistencia = new javax.swing.JLabel();
        lblReporte = new javax.swing.JLabel();
        lblUsuarioActvo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(69, 90, 100));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHora.setText("hora fecha");
        lblHora.setName("lblHora"); // NOI18N
        jPanel2.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, -1, -1));

        jLabel2.setText("hombol maternal");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        lblLogo.setText("logo ");
        lblLogo.setName("lblLogo"); // NOI18N
        jPanel2.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));

        btnAjustes.setText("ajustes");
        btnAjustes.setName("btnAjustes"); // NOI18N
        jPanel2.add(btnAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        btnCerrarSesion.setText("cerrar sesion");
        btnCerrarSesion.setName("btnCerrarSesion"); // NOI18N
        jPanel2.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        lblNota.setText("notas");
        lblNota.setName("lblNotas"); // NOI18N
        jPanel2.add(lblNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        lblInscripcion.setText("inscripcion");
        lblInscripcion.setName("lblInscripcion"); // NOI18N
        jPanel2.add(lblInscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        lblPago.setText("pagos");
        lblPago.setName("lblPagos"); // NOI18N
        jPanel2.add(lblPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        lblUsuario.setText("usuario");
        lblUsuario.setName("lblUsuario"); // NOI18N
        jPanel2.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        lblAsistencia.setText("asistencia");
        lblAsistencia.setName("lblAsistencia"); // NOI18N
        jPanel2.add(lblAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        lblReporte.setText("reportes");
        lblReporte.setName("lblReportes"); // NOI18N
        jPanel2.add(lblReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, -1, -1));

        lblUsuarioActvo.setText("usuario activo");
        lblUsuarioActvo.setName("lblUsuarioActivo"); // NOI18N
        jPanel2.add(lblUsuarioActvo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 370));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjustes;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAsistencia;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblInscripcion;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNota;
    private javax.swing.JLabel lblPago;
    private javax.swing.JLabel lblReporte;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuarioActvo;
    // End of variables declaration//GEN-END:variables
}
