/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Coordinador;
import VO.AlumnoVO;
import VO.NotaVO;
import VO.PagoVO;
import VO.RepresentanteVO;
import java.awt.Image;
import java.sql.Connection;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.text.Element;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Lenovo
 */
public class frmMenuReportes extends javax.swing.JFrame {

    private Coordinador coordinador;
    private final ImageIcon iconLogo = new javax.swing.ImageIcon(getClass().getResource("/Recursos/logo.png"));
    private String ampm;
    private String hora;
    private String minutos;
    private String segundos;
    private long i=0;
    private int id;

    /**
     * Creates new form frmMenu
     */
    public frmMenuReportes() {
        this.setlook();
         initComponents();
        setLocationRelativeTo(null);
    }
    
    public void setlook() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void ajustar(JLabel label, ImageIcon icon) {
        //esta funcion ajusta un icono(parametro) al tamaño del label (parametro)
        Icon icono = new ImageIcon(icon.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_DEFAULT));
        label.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmDatosConstanciaInscripcion = new javax.swing.JFrame();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        lblNombres = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        frmDatosConstanciaPago = new javax.swing.JFrame();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        txtCodigo1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        btnBuscar1 = new javax.swing.JButton();
        lblNombres1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblMes = new javax.swing.JLabel();
        frmDatosNumeroCedula = new javax.swing.JFrame();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        txtCodigo2 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        btnBuscar2 = new javax.swing.JButton();
        lblNombres2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNacimiento = new javax.swing.JTextField();
        frmDatosConstanciaEstudio = new javax.swing.JFrame();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        txtCodigo3 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        btnBuscar3 = new javax.swing.JButton();
        lblNombres3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        frmDatosBoletin = new javax.swing.JFrame();
        jPanel11 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        txtCodigo4 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        btnBuscar4 = new javax.swing.JButton();
        lblNombres4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbxLapso = new javax.swing.JComboBox<>();
        frmDatosBoletin2 = new javax.swing.JFrame();
        jPanel12 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        txtCodigo5 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        btnBuscar5 = new javax.swing.JButton();
        lblNombres5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cbxLapso1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bntAtras = new javax.swing.JButton();
        lblUsuarioActvo = new javax.swing.JLabel();
        btnNotas = new javax.swing.JButton();
        btnPagos = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        btnAsistencia = new javax.swing.JButton();
        btnSeccion = new javax.swing.JButton();
        btnInscripcion = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnDocentes = new javax.swing.JButton();
        btnReportes1 = new javax.swing.JButton();

        frmDatosConstanciaInscripcion.setMinimumSize(new java.awt.Dimension(290, 225));
        frmDatosConstanciaInscripcion.setResizable(false);
        frmDatosConstanciaInscripcion.setSize(new java.awt.Dimension(290, 225));
        frmDatosConstanciaInscripcion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(69, 90, 100));
        jPanel7.setMaximumSize(new java.awt.Dimension(290, 120));
        jPanel7.setMinimumSize(new java.awt.Dimension(290, 120));
        jPanel7.setPreferredSize(new java.awt.Dimension(290, 120));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Datos para Reporte:");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 30));

        jButton12.setText("Aceptar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 80, -1));

        jButton13.setText("Cancelar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 80, -1));

        txtCodigo.setName("txtCodigoAlumno"); // NOI18N
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        jPanel7.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 70, 30));

        jLabel30.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Codigo alumno");
        jLabel30.setName("lbl"); // NOI18N
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 30));

        btnBuscar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icon_buscar24.png"))); // NOI18N
        btnBuscar.setName("btnBuscar"); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel7.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 30, -1));

        lblNombres.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNombres.setForeground(new java.awt.Color(255, 255, 255));
        lblNombres.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 270, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombres y apellidos");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 30));

        frmDatosConstanciaInscripcion.getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 200));

        frmDatosConstanciaPago.setMinimumSize(new java.awt.Dimension(290, 225));
        frmDatosConstanciaPago.setResizable(false);
        frmDatosConstanciaPago.setSize(new java.awt.Dimension(290, 225));
        frmDatosConstanciaPago.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(69, 90, 100));
        jPanel8.setMaximumSize(new java.awt.Dimension(290, 120));
        jPanel8.setMinimumSize(new java.awt.Dimension(290, 120));
        jPanel8.setPreferredSize(new java.awt.Dimension(290, 120));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Datos para Reporte:");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 30));

        jButton14.setText("Aceptar");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 80, -1));

        jButton15.setText("Cancelar");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 80, -1));

        txtCodigo1.setName("txtCodigoAlumno"); // NOI18N
        txtCodigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigo1ActionPerformed(evt);
            }
        });
        txtCodigo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigo1KeyTyped(evt);
            }
        });
        jPanel8.add(txtCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 70, 30));

        jLabel31.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Codigo alumno");
        jLabel31.setName("lbl"); // NOI18N
        jPanel8.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 30));

        btnBuscar1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnBuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icon_buscar24.png"))); // NOI18N
        btnBuscar1.setName("btnBuscar"); // NOI18N
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });
        jPanel8.add(btnBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 30, -1));

        lblNombres1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNombres1.setForeground(new java.awt.Color(255, 255, 255));
        lblNombres1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.add(lblNombres1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 200, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ultimo mes pago:");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Alumno:");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 70, 30));

        lblMes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMes.setForeground(new java.awt.Color(255, 255, 255));
        lblMes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.add(lblMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 130, 30));

        frmDatosConstanciaPago.getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 200));

        frmDatosNumeroCedula.setMinimumSize(new java.awt.Dimension(290, 225));
        frmDatosNumeroCedula.setResizable(false);
        frmDatosNumeroCedula.setSize(new java.awt.Dimension(290, 225));
        frmDatosNumeroCedula.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(69, 90, 100));
        jPanel9.setMaximumSize(new java.awt.Dimension(290, 120));
        jPanel9.setMinimumSize(new java.awt.Dimension(290, 120));
        jPanel9.setPreferredSize(new java.awt.Dimension(290, 120));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Datos para Reporte:");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 30));

        jButton16.setText("Aceptar");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 80, -1));

        jButton17.setText("Cancelar");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 80, -1));

        txtCodigo2.setName("txtCodigoAlumno"); // NOI18N
        txtCodigo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigo2ActionPerformed(evt);
            }
        });
        txtCodigo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigo2KeyTyped(evt);
            }
        });
        jPanel9.add(txtCodigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 70, 30));

        jLabel32.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Codigo alumno");
        jLabel32.setName("lbl"); // NOI18N
        jPanel9.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 30));

        btnBuscar2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnBuscar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icon_buscar24.png"))); // NOI18N
        btnBuscar2.setName("btnBuscar"); // NOI18N
        btnBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar2ActionPerformed(evt);
            }
        });
        jPanel9.add(btnBuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 30, -1));

        lblNombres2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNombres2.setForeground(new java.awt.Color(255, 255, 255));
        lblNombres2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.add(lblNombres2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 200, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Lugar de Nacimiento:");
        jPanel9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 150, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Alumno:");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 70, 30));

        txtNacimiento.setName("txtCodigoAlumno"); // NOI18N
        txtNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNacimientoActionPerformed(evt);
            }
        });
        txtNacimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNacimientoKeyTyped(evt);
            }
        });
        jPanel9.add(txtNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 120, 30));

        frmDatosNumeroCedula.getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 200));

        frmDatosConstanciaEstudio.setMinimumSize(new java.awt.Dimension(290, 225));
        frmDatosConstanciaEstudio.setResizable(false);
        frmDatosConstanciaEstudio.setSize(new java.awt.Dimension(290, 225));
        frmDatosConstanciaEstudio.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(69, 90, 100));
        jPanel10.setMaximumSize(new java.awt.Dimension(290, 120));
        jPanel10.setMinimumSize(new java.awt.Dimension(290, 120));
        jPanel10.setPreferredSize(new java.awt.Dimension(290, 120));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Datos para Reporte:");
        jPanel10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 30));

        jButton18.setText("Aceptar");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 80, -1));

        jButton19.setText("Cancelar");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 80, -1));

        txtCodigo3.setName("txtCodigoAlumno"); // NOI18N
        txtCodigo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigo3ActionPerformed(evt);
            }
        });
        txtCodigo3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigo3KeyTyped(evt);
            }
        });
        jPanel10.add(txtCodigo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 70, 30));

        jLabel33.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Codigo alumno");
        jLabel33.setName("lbl"); // NOI18N
        jPanel10.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 30));

        btnBuscar3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnBuscar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icon_buscar24.png"))); // NOI18N
        btnBuscar3.setName("btnBuscar"); // NOI18N
        btnBuscar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar3ActionPerformed(evt);
            }
        });
        jPanel10.add(btnBuscar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 30, -1));

        lblNombres3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNombres3.setForeground(new java.awt.Color(255, 255, 255));
        lblNombres3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.add(lblNombres3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 270, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nombres y apellidos");
        jPanel10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 30));

        frmDatosConstanciaEstudio.getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 200));

        frmDatosBoletin.setMaximumSize(new java.awt.Dimension(290, 225));
        frmDatosBoletin.setMinimumSize(new java.awt.Dimension(290, 225));
        frmDatosBoletin.setPreferredSize(new java.awt.Dimension(290, 225));
        frmDatosBoletin.setResizable(false);
        frmDatosBoletin.setSize(new java.awt.Dimension(290, 225));
        frmDatosBoletin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(69, 90, 100));
        jPanel11.setMaximumSize(new java.awt.Dimension(290, 120));
        jPanel11.setMinimumSize(new java.awt.Dimension(290, 120));
        jPanel11.setPreferredSize(new java.awt.Dimension(290, 120));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Datos para Reporte:");
        jPanel11.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 30));

        jButton20.setText("Aceptar");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 80, -1));

        jButton21.setText("Cancelar");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 80, -1));

        txtCodigo4.setName("txtCodigoAlumno"); // NOI18N
        txtCodigo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigo4ActionPerformed(evt);
            }
        });
        txtCodigo4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigo4KeyTyped(evt);
            }
        });
        jPanel11.add(txtCodigo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 70, 20));

        jLabel34.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Codigo alumno");
        jLabel34.setName("lbl"); // NOI18N
        jPanel11.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 20));

        btnBuscar4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnBuscar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icon_buscar24.png"))); // NOI18N
        btnBuscar4.setName("btnBuscar"); // NOI18N
        btnBuscar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar4ActionPerformed(evt);
            }
        });
        jPanel11.add(btnBuscar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 30, 20));

        lblNombres4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNombres4.setForeground(new java.awt.Color(255, 255, 255));
        lblNombres4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.add(lblNombres4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 270, 20));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nombres y apellidos");
        jPanel11.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Lapso");
        jPanel11.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, 20));

        cbxLapso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1ERO", "2DO", "3RO" }));
        cbxLapso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLapsoActionPerformed(evt);
            }
        });
        jPanel11.add(cbxLapso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 70, -1));

        frmDatosBoletin.getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 240));

        frmDatosBoletin2.setMaximumSize(new java.awt.Dimension(290, 225));
        frmDatosBoletin2.setMinimumSize(new java.awt.Dimension(290, 225));
        frmDatosBoletin2.setPreferredSize(new java.awt.Dimension(290, 225));
        frmDatosBoletin2.setResizable(false);
        frmDatosBoletin2.setSize(new java.awt.Dimension(290, 225));
        frmDatosBoletin2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(69, 90, 100));
        jPanel12.setMaximumSize(new java.awt.Dimension(290, 120));
        jPanel12.setMinimumSize(new java.awt.Dimension(290, 120));
        jPanel12.setPreferredSize(new java.awt.Dimension(290, 120));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Datos para Reporte:");
        jPanel12.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 30));

        jButton22.setText("Aceptar");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 163, 80, 20));

        jButton23.setText("Cancelar");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 163, 80, 20));

        txtCodigo5.setName("txtCodigoAlumno"); // NOI18N
        txtCodigo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigo5ActionPerformed(evt);
            }
        });
        txtCodigo5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigo5KeyTyped(evt);
            }
        });
        jPanel12.add(txtCodigo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 70, 20));

        jLabel35.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Codigo alumno");
        jLabel35.setName("lbl"); // NOI18N
        jPanel12.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 20));

        btnBuscar5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnBuscar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icon_buscar24.png"))); // NOI18N
        btnBuscar5.setName("btnBuscar"); // NOI18N
        btnBuscar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar5ActionPerformed(evt);
            }
        });
        jPanel12.add(btnBuscar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 30, 20));

        lblNombres5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNombres5.setForeground(new java.awt.Color(255, 255, 255));
        lblNombres5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel12.add(lblNombres5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 270, 20));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nombres y apellidos");
        jPanel12.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Lapso");
        jPanel12.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, 20));

        cbxLapso1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1ERO", "2DO", "3RO" }));
        cbxLapso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLapso1ActionPerformed(evt);
            }
        });
        jPanel12.add(cbxLapso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 70, -1));

        frmDatosBoletin2.getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 240));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(69, 90, 100));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 153), new java.awt.Color(0, 51, 153)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Reportes");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 340, 110));

        bntAtras.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        bntAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icon_exit24.png"))); // NOI18N
        bntAtras.setText("Salir");
        bntAtras.setName("bntAtras"); // NOI18N
        bntAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAtrasActionPerformed(evt);
            }
        });
        jPanel2.add(bntAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 130, 30));

        lblUsuarioActvo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblUsuarioActvo.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarioActvo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuarioActvo.setText("usuario activo");
        lblUsuarioActvo.setName("lblUsuarioActivo"); // NOI18N
        jPanel2.add(lblUsuarioActvo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 170, 30));

        btnNotas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNotas.setText("Lista de Utiles Grupo 2");
        btnNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotasActionPerformed(evt);
            }
        });
        jPanel2.add(btnNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 160, 70));

        btnPagos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnPagos.setText("Constancia de Estudio");
        btnPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagosActionPerformed(evt);
            }
        });
        jPanel2.add(btnPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 160, 70));

        btnUsuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnUsuario.setText("Lista de Utiles Grupo 1");
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(btnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 160, 70));

        btnAsistencia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAsistencia.setText("Solvencia de Pago");
        btnAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsistenciaActionPerformed(evt);
            }
        });
        jPanel2.add(btnAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 160, 70));

        btnSeccion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSeccion.setText("Lista de Utiles Grupo 3");
        btnSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeccionActionPerformed(evt);
            }
        });
        jPanel2.add(btnSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 160, 70));

        btnInscripcion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnInscripcion.setText("Constancia de Inscripcion");
        btnInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscripcionActionPerformed(evt);
            }
        });
        jPanel2.add(btnInscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 180, 70));

        btnReportes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnReportes.setText("Boletin Informativo");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        jPanel2.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 160, 30));

        btnDocentes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnDocentes.setText("Numero Cedula Escolar");
        btnDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocentesActionPerformed(evt);
            }
        });
        jPanel2.add(btnDocentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 180, 70));

        btnReportes1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnReportes1.setText("Boletin Informativo 2");
        btnReportes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportes1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnReportes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 160, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 370));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsistenciaActionPerformed
 this.frmDatosConstanciaPago.setLocationRelativeTo(null);
 this.frmDatosConstanciaPago.setSize(290, 200);
 this.frmDatosConstanciaPago.setVisible(true);   
    }//GEN-LAST:event_btnAsistenciaActionPerformed

    private void btnSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeccionActionPerformed
    try {
        Connection conexion= null;
        Conexion.ConexionBd conexiondb = new Conexion.ConexionBd();
        conexion = conexiondb.getConnection();
            String dir = coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte()+ "\\lista3grupo.jrxml";
            Map<String, Object> p2 = new HashMap<>();
            p2.put("ruta", coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte());
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conexion);
            JasperViewer visor = new JasperViewer(mostrarReporte, false);
            visor.setVisible(true);
        } catch (JRException ex) {
            coordinador.getLogica().mensajeError("OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex);
    } 
    }//GEN-LAST:event_btnSeccionActionPerformed

    private void btnInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscripcionActionPerformed
 this.frmDatosConstanciaInscripcion.setLocationRelativeTo(null);
 this.frmDatosConstanciaInscripcion.setSize(290, 200);
 this.frmDatosConstanciaInscripcion.setVisible(true); 
    }//GEN-LAST:event_btnInscripcionActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
     this.frmDatosBoletin.setLocationRelativeTo(null);
 this.frmDatosBoletin.setSize(290, 200);
 this.frmDatosBoletin.setVisible(true); 
        
        
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
    try {
        Connection conexion= null;
        Conexion.ConexionBd conexiondb = new Conexion.ConexionBd();
        conexion = conexiondb.getConnection();
            String dir = coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte()+ "\\lista1ergrupo.jrxml";
            Map<String, Object> p2 = new HashMap<>();
            p2.put("ruta", coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte());
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conexion);
            JasperViewer visor = new JasperViewer(mostrarReporte, false);
            visor.setVisible(true);
        } catch (JRException ex) {
            coordinador.getLogica().mensajeError("OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex);
    }   
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagosActionPerformed
 this.frmDatosConstanciaEstudio.setLocationRelativeTo(null);
 this.frmDatosConstanciaEstudio.setSize(290, 200);
 this.frmDatosConstanciaEstudio.setVisible(true); 
    }//GEN-LAST:event_btnPagosActionPerformed

    private void bntAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAtrasActionPerformed
    this.dispose();
    }//GEN-LAST:event_bntAtrasActionPerformed

    private void btnDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocentesActionPerformed
 this.frmDatosNumeroCedula.setLocationRelativeTo(null);
 this.frmDatosNumeroCedula.setSize(290, 200);
 this.frmDatosNumeroCedula.setVisible(true); 
    }//GEN-LAST:event_btnDocentesActionPerformed

    private void btnNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotasActionPerformed
    try {
        Connection conexion= null;
        Conexion.ConexionBd conexiondb = new Conexion.ConexionBd();
        conexion = conexiondb.getConnection();
            String dir = coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte()+ "\\lista2dogrupo.jrxml";
            Map<String, Object> p2 = new HashMap<>();
            p2.put("ruta", coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte());
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conexion);
            JasperViewer visor = new JasperViewer(mostrarReporte, false);
            visor.setVisible(true);
        } catch (JRException ex) {
            coordinador.getLogica().mensajeError("OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex);
    } 
    }//GEN-LAST:event_btnNotasActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        if (!lblNombres.getText().equals("")) {
            try {
                Connection conexion = null;
                Conexion.ConexionBd conexiondb = new Conexion.ConexionBd();
                conexion = conexiondb.getConnection();
                String dir = coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte() + "\\Constancia de Inscripcion.jrxml";
                double valorMatricula = 0 ;
                valorMatricula = (coordinador.getVariablesDAO().consultarVariables().getPrecio_cuota() + (coordinador.getVariablesDAO().consultarVariables().getPrecio_cuota() * coordinador.getVariablesDAO().consultarVariables().getIva()/ 100)) * 12;
                
                Map<String, Object> p2 = new HashMap<>();
                p2.put("id", id);
                p2.put("ruta", coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte());
                p2.put("matricula", valorMatricula);;
                p2.put("total", (valorMatricula+coordinador.getVariablesDAO().consultarVariables().getSeguro()));
                p2.put("anio_anterior", coordinador.getVariablesDAO().consultarVariables().getPeriodo_actual().substring(0, 4));
                p2.put("anio_siguiente", coordinador.getVariablesDAO().consultarVariables().getPeriodo_actual().substring(5, 9));
                JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
                JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conexion);
                JasperViewer visor = new JasperViewer(mostrarReporte, false);
                visor.setVisible(true);
                lblNombres.setText("");
                txtCodigo.setText("");
            } catch (JRException ex) {
                coordinador.getLogica().mensajeError("OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex);
                this.dispose();
            }
           
        }else{
               coordinador.getLogica().mensajeError("Por favor consulte un alumno");
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
                        lblNombres.setText("");
                txtCodigo.setText("");
        this.frmDatosConstanciaInscripcion.setVisible(false); 
    }//GEN-LAST:event_jButton13ActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped

    }//GEN-LAST:event_txtCodigoKeyTyped

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (!txtCodigo.getText().isEmpty()) {
            id = Integer.parseInt(txtCodigo.getText());
            AlumnoVO alumnoVO = coordinador.consultarAlumno(txtCodigo.getText().trim());
            if (alumnoVO.getPrimer_nombre() != null) {
                //datos del alumno
                lblNombres.setText(alumnoVO.getPrimer_nombre()+" "+alumnoVO.getSegundo_nombre()+" "+alumnoVO.getPrimer_apellido()+" "+alumnoVO.getSegundo_apellido());
              } else{
                     coordinador.getLogica().mensajeError("Codigo no existe");
            }
        }else {
            coordinador.getLogica().mensajeAdvertencia("Ingrese un codigo");
        }
       
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        if (!lblNombres1.getText().equals("")) {
            try {
                Connection conexion = null;
                Conexion.ConexionBd conexiondb = new Conexion.ConexionBd();
                conexion = conexiondb.getConnection();
                String dir = coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte() + "\\solvenciaPago.jrxml";

                Map<String, Object> p2 = new HashMap<>();
                p2.put("id", id);
                p2.put("ruta", coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte());
                p2.put("mes", lblMes.getText());
                JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
                JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conexion);
                JasperViewer visor = new JasperViewer(mostrarReporte, false);
                visor.setVisible(true);
                lblNombres1.setText("");
                txtCodigo1.setText("");
                lblMes.setText("");
            } catch (JRException ex) {
                coordinador.getLogica().mensajeError("OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex);
                this.dispose();
            }
           
        }else{
               coordinador.getLogica().mensajeError("Por favor consulte un alumno");
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
                        lblNombres1.setText("");
                txtCodigo1.setText("");
                lblMes.setText("");
        this.frmDatosConstanciaPago.setVisible(false);        
    }//GEN-LAST:event_jButton15ActionPerformed

    private void txtCodigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo1ActionPerformed

    private void txtCodigo1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigo1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo1KeyTyped

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        if (!txtCodigo1.getText().isEmpty()) {
            id = Integer.parseInt(txtCodigo1.getText());
            AlumnoVO alumnoVO = coordinador.consultarAlumno(txtCodigo1.getText().trim());
            if (alumnoVO.getPrimer_nombre() != null) {
                //datos del alumno
                lblNombres1.setText(alumnoVO.getPrimer_nombre()+" "+alumnoVO.getSegundo_nombre()+" "+alumnoVO.getPrimer_apellido()+" "+alumnoVO.getSegundo_apellido());
                String consultarPago = consultarPago(String.valueOf(id));
                lblMes.setText(consultarPago);
            } else{
                     coordinador.getLogica().mensajeError("Codigo no existe");
            }
        }else {
            coordinador.getLogica().mensajeAdvertencia("Ingrese un codigo");
        }
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        if (!lblNombres2.getText().equals("")) {
            if (!txtNacimiento.getText().equals("")) {
            try {
                Connection conexion = null;
                Conexion.ConexionBd conexiondb = new Conexion.ConexionBd();
                conexion = conexiondb.getConnection();
                String dir = coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte() + "\\numerocudelaescolar.jrxml";

                Map<String, Object> p2 = new HashMap<>();
                p2.put("id", id);
                p2.put("lugar", txtNacimiento.getText());
                JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
                JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conexion);
                JasperViewer visor = new JasperViewer(mostrarReporte, false);
                visor.setVisible(true);
                lblNombres2.setText("");
                txtCodigo2.setText("");
                txtNacimiento.setText("");
            } catch (JRException ex) {
                coordinador.getLogica().mensajeError("OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex);
                this.dispose();
            }
           }else{
               coordinador.getLogica().mensajeError("Por favor ingrese el lugar de nacimiento");
        }
        }else{
               coordinador.getLogica().mensajeError("Por favor consulte un alumno");
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
                        lblNombres2.setText("");
                txtCodigo2.setText("");
                txtNacimiento.setText("");
        this.frmDatosNumeroCedula.setVisible(false);     
    }//GEN-LAST:event_jButton17ActionPerformed

    private void txtCodigo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo2ActionPerformed

    private void txtCodigo2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigo2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo2KeyTyped

    private void btnBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar2ActionPerformed
        if (!txtCodigo2.getText().isEmpty()) {
            id = Integer.parseInt(txtCodigo2.getText());
            AlumnoVO alumnoVO = coordinador.consultarAlumno(txtCodigo2.getText().trim());
            if (alumnoVO.getPrimer_nombre() != null) {
                //datos del alumno
                lblNombres2.setText(alumnoVO.getPrimer_nombre()+" "+alumnoVO.getSegundo_nombre()+" "+alumnoVO.getPrimer_apellido()+" "+alumnoVO.getSegundo_apellido());
              } else{
                     coordinador.getLogica().mensajeError("Codigo no existe");
            }
        }else {
            coordinador.getLogica().mensajeAdvertencia("Ingrese un codigo");
        }
    }//GEN-LAST:event_btnBuscar2ActionPerformed

    private void txtNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNacimientoActionPerformed

    private void txtNacimientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNacimientoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNacimientoKeyTyped

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        if (!lblNombres3.getText().equals("")) {
            try {
                Connection conexion = null;
                Conexion.ConexionBd conexiondb = new Conexion.ConexionBd();
                conexion = conexiondb.getConnection();
                String dir = coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte() + "\\constancia.jrxml";
          
                Map<String, Object> p2 = new HashMap<>();
                p2.put("id", id);
                p2.put("ruta", coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte());
                JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
                JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conexion);
                JasperViewer visor = new JasperViewer(mostrarReporte, false);
                visor.setVisible(true);
                lblNombres3.setText("");
                txtCodigo3.setText("");
            } catch (JRException ex) {
                coordinador.getLogica().mensajeError("OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex);
                this.dispose();
            }
           
        }else{
               coordinador.getLogica().mensajeError("Por favor consulte un alumno");
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
                        lblNombres3.setText("");
                txtCodigo3.setText("");
        this.frmDatosConstanciaEstudio.setVisible(false); 
    }//GEN-LAST:event_jButton19ActionPerformed

    private void txtCodigo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo3ActionPerformed

    private void txtCodigo3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigo3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo3KeyTyped

    private void btnBuscar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar3ActionPerformed
        if (!txtCodigo3.getText().isEmpty()) {
            id = Integer.parseInt(txtCodigo3.getText());
            AlumnoVO alumnoVO = coordinador.consultarAlumno(txtCodigo3.getText().trim());
            if (alumnoVO.getPrimer_nombre() != null) {
                //datos del alumno
                lblNombres3.setText(alumnoVO.getPrimer_nombre()+" "+alumnoVO.getSegundo_nombre()+" "+alumnoVO.getPrimer_apellido()+" "+alumnoVO.getSegundo_apellido());
              } else{
                     coordinador.getLogica().mensajeError("Codigo no existe");
            }
        }else {
            coordinador.getLogica().mensajeAdvertencia("Ingrese un codigo");
        }
    }//GEN-LAST:event_btnBuscar3ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
                if (lblNombres4.getText().isEmpty()) {
                    coordinador.getLogica().mensajeError("Por Favor consulte primero a un alumno");
                }else{   
//llenar parametros a enviar
        if (!obtenerDatos2(String.valueOf(id))) {
            coordinador.getLogica().mensajeError("No existen notas registradas para el alumno: " + lblNombres4.getText() + " para el lapso seleccionado");
        } else {
            try {
                Connection conexion = null;
                Conexion.ConexionBd conexiondb = new Conexion.ConexionBd();
                conexion = conexiondb.getConnection();
                String dir = coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte() + "\\boletin1.jrxml";
                //obtengo valores a pasar
                NotaVO notaVO = obtenerDatos(String.valueOf(id));
                Map<String, Object> p2 = new HashMap<>();
                p2.put("id", id);
                p2.put("lapso", cbxLapso.getSelectedItem().toString());
                p2.put("ruta", coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte());
                p2.put("parameter1", notaVO.getFormacion_personal_social()[0].substring(2,  notaVO.getFormacion_personal_social()[0].length()));
                p2.put("parameter2", notaVO.getFormacion_personal_social()[1].substring(2,  notaVO.getFormacion_personal_social()[1].length()));
                p2.put("parameter3", notaVO.getFormacion_personal_social()[2].substring(2,  notaVO.getFormacion_personal_social()[2].length()));
                p2.put("parameter4", notaVO.getFormacion_personal_social()[3].substring(2,  notaVO.getFormacion_personal_social()[3].length()));
                p2.put("parameter5", notaVO.getFormacion_personal_social()[4].substring(2,  notaVO.getFormacion_personal_social()[4].length()));
                p2.put("parameter6", notaVO.getFormacion_personal_social()[5].substring(2,  notaVO.getFormacion_personal_social()[5].length()));
                p2.put("parameter7", notaVO.getFormacion_personal_social()[6].substring(2,  notaVO.getFormacion_personal_social()[6].length()));
                p2.put("parameter8", notaVO.getFormacion_personal_social()[7].substring(2,  notaVO.getFormacion_personal_social()[7].length()));
                p2.put("parameter9", notaVO.getFormacion_personal_social()[8].substring(2,  notaVO.getFormacion_personal_social()[8].length()));
                //
                p2.put("parameter10", notaVO.getRelacion_ambiente()[0].substring(2,  notaVO.getRelacion_ambiente()[0].length()));
                p2.put("parameter11", notaVO.getRelacion_ambiente()[1].substring(2,  notaVO.getRelacion_ambiente()[1].length()));
                p2.put("parameter12", notaVO.getRelacion_ambiente()[2].substring(2,  notaVO.getRelacion_ambiente()[2].length()));
                p2.put("parameter13", notaVO.getRelacion_ambiente()[3].substring(2,  notaVO.getRelacion_ambiente()[3].length()));
                p2.put("parameter14", notaVO.getRelacion_ambiente()[4].substring(2,  notaVO.getRelacion_ambiente()[4].length()));
                p2.put("parameter15", notaVO.getRelacion_ambiente()[5].substring(2,  notaVO.getRelacion_ambiente()[5].length()));
                p2.put("parameter16", notaVO.getRelacion_ambiente()[6].substring(2,  notaVO.getRelacion_ambiente()[6].length()));
                p2.put("parameter17", notaVO.getRelacion_ambiente()[7].substring(2,  notaVO.getRelacion_ambiente()[7].length()));
                p2.put("parameter18", notaVO.getRelacion_ambiente()[8].substring(2,  notaVO.getRelacion_ambiente()[8].length()));
                p2.put("parameter19", notaVO.getRelacion_ambiente()[9].substring(3,  notaVO.getRelacion_ambiente()[9].length()));
                //
                p2.put("parameter20", notaVO.getComunicacion_presentacion()[0].substring(2,  notaVO.getComunicacion_presentacion()[0].length()));
                p2.put("parameter21", notaVO.getComunicacion_presentacion()[1].substring(2,  notaVO.getComunicacion_presentacion()[1].length()));
                p2.put("parameter22", notaVO.getComunicacion_presentacion()[2].substring(2,  notaVO.getComunicacion_presentacion()[2].length()));
                p2.put("parameter23", notaVO.getComunicacion_presentacion()[3].substring(2,  notaVO.getComunicacion_presentacion()[3].length()));
                p2.put("parameter24", notaVO.getComunicacion_presentacion()[4].substring(2,  notaVO.getComunicacion_presentacion()[4].length()));
                p2.put("parameter25", notaVO.getComunicacion_presentacion()[5].substring(2,  notaVO.getComunicacion_presentacion()[5].length()));
                p2.put("parameter26", notaVO.getComunicacion_presentacion()[6].substring(2,  notaVO.getComunicacion_presentacion()[6].length()));
                p2.put("parameter27", notaVO.getComunicacion_presentacion()[7].substring(2,  notaVO.getComunicacion_presentacion()[7].length()));
                p2.put("parameter28", notaVO.getComunicacion_presentacion()[8].substring(2,  notaVO.getComunicacion_presentacion()[8].length()));
                p2.put("parameter29", notaVO.getComunicacion_presentacion()[9].substring(3,  notaVO.getComunicacion_presentacion()[9].length()));
                p2.put("parameter30", notaVO.getComunicacion_presentacion()[10].substring(3, notaVO.getComunicacion_presentacion()[10].length()));
                p2.put("parameter31", notaVO.getComunicacion_presentacion()[11].substring(3,  notaVO.getComunicacion_presentacion()[11].length()));
                p2.put("parameter32", notaVO.getComunicacion_presentacion()[12].substring(3,  notaVO.getComunicacion_presentacion()[12].length()));
                p2.put("parameter33", notaVO.getComunicacion_presentacion()[13].substring(3,  notaVO.getComunicacion_presentacion()[13].length()));
                
                JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
                JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conexion);
                JasperViewer visor = new JasperViewer(mostrarReporte, false);
                visor.setVisible(true);
            } catch (JRException ex) {
                coordinador.getLogica().mensajeError("OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex);
            }
        }
 }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
                        lblNombres4.setText("");
                txtCodigo4.setText("");
                cbxLapso.setSelectedIndex(0);
        this.frmDatosBoletin.setVisible(false); 
    }//GEN-LAST:event_jButton21ActionPerformed

    private void txtCodigo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo4ActionPerformed

    private void txtCodigo4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigo4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo4KeyTyped

    private void btnBuscar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar4ActionPerformed
        if (!txtCodigo4.getText().isEmpty()) {
            id = Integer.parseInt(txtCodigo4.getText());
            AlumnoVO alumnoVO = coordinador.consultarAlumno(txtCodigo4.getText().trim());
            if (alumnoVO.getPrimer_nombre() != null) {
                //datos del alumno
                lblNombres4.setText(alumnoVO.getPrimer_nombre() + " " + alumnoVO.getSegundo_nombre() + " " + alumnoVO.getPrimer_apellido() + " " + alumnoVO.getSegundo_apellido());

                //llenar parametros a enviar
                if (!obtenerDatos2(String.valueOf(id))) {
                    coordinador.getLogica().mensajeError("No existen notas registradas para el alumno: " + lblNombres4.getText() + " para el lapso seleccionado");
                    lblNombres4.setText("");
                    txtCodigo4.setText("");
                                    cbxLapso.setSelectedIndex(0);
                }
            } else {
                     coordinador.getLogica().mensajeError("Codigo no existe");
                                         lblNombres4.setText("");
                    txtCodigo4.setText("");
                                    cbxLapso.setSelectedIndex(0);
            }
        }else {
            coordinador.getLogica().mensajeAdvertencia("Ingrese un codigo");
        }
    }//GEN-LAST:event_btnBuscar4ActionPerformed

    private void cbxLapsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLapsoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLapsoActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
               if (lblNombres5.getText().isEmpty()) {
                    coordinador.getLogica().mensajeError("Por Favor consulte primero a un alumno");
                }else{   
//llenar parametros a enviar
        if (!obtenerDatos2(String.valueOf(id))) {
            coordinador.getLogica().mensajeError("No existen notas registradas para el alumno: " + lblNombres5.getText() + " para el lapso seleccionado");
        } else {
            try {
                Connection conexion = null;
                Conexion.ConexionBd conexiondb = new Conexion.ConexionBd();
                conexion = conexiondb.getConnection();
                String dir = coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte() + "\\boletin2.jrxml";
                //obtengo valores a pasar
                NotaVO notaVO = obtenerDatos(String.valueOf(id));
                Map<String, Object> p2 = new HashMap<>();
                p2.put("id", id);
                p2.put("lapso", cbxLapso1.getSelectedItem().toString());
                p2.put("ruta", coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte());
                p2.put("parameter1", notaVO.getIndicadores_evaluados()[0].substring(2,  notaVO.getIndicadores_evaluados()[0].length()));
                p2.put("parameter2", notaVO.getIndicadores_evaluados()[1].substring(2,  notaVO.getIndicadores_evaluados()[1].length()));
                p2.put("parameter3", notaVO.getIndicadores_evaluados()[2].substring(2,  notaVO.getIndicadores_evaluados()[2].length()));
                p2.put("parameter4", notaVO.getIndicadores_evaluados()[3].substring(2,  notaVO.getIndicadores_evaluados()[3].length()));
                p2.put("parameter5", notaVO.getIndicadores_evaluados()[4].substring(2,  notaVO.getIndicadores_evaluados()[4].length()));
                p2.put("parameter6", notaVO.getIndicadores_evaluados()[5].substring(2,  notaVO.getIndicadores_evaluados()[5].length()));
                p2.put("parameter7", notaVO.getIndicadores_evaluados()[6].substring(2,  notaVO.getIndicadores_evaluados()[6].length()));
                p2.put("parameter8", notaVO.getIndicadores_evaluados()[7].substring(2,  notaVO.getIndicadores_evaluados()[7].length()));
                p2.put("parameter9", notaVO.getIndicadores_evaluados()[8].substring(2,  notaVO.getIndicadores_evaluados()[8].length()));
                p2.put("parameter10", notaVO.getIndicadores_evaluados()[9].substring(3,  notaVO.getIndicadores_evaluados()[9].length()));
                //
                p2.put("parameter11", notaVO.getIndicadores_evaluados()[10].substring(3,  notaVO.getIndicadores_evaluados()[10].length()));
                p2.put("parameter12", notaVO.getIndicadores_evaluados()[11].substring(3,  notaVO.getIndicadores_evaluados()[11].length()));
                p2.put("parameter13", notaVO.getIndicadores_evaluados()[12].substring(3,  notaVO.getIndicadores_evaluados()[12].length()));
                p2.put("parameter14", notaVO.getIndicadores_evaluados()[13].substring(3,  notaVO.getIndicadores_evaluados()[13].length()));
                p2.put("parameter15", notaVO.getIndicadores_evaluados()[14].substring(3,  notaVO.getIndicadores_evaluados()[14].length()));
                p2.put("parameter16", notaVO.getIndicadores_evaluados()[15].substring(3,  notaVO.getIndicadores_evaluados()[15].length()));
                p2.put("parameter17", notaVO.getIndicadores_evaluados()[16].substring(3,  notaVO.getIndicadores_evaluados()[16].length()));
                p2.put("parameter18", notaVO.getIndicadores_evaluados()[17].substring(3,  notaVO.getIndicadores_evaluados()[17].length()));
                p2.put("parameter19", notaVO.getIndicadores_evaluados()[18].substring(3,  notaVO.getIndicadores_evaluados()[18].length()));
                //
                p2.put("parameter20", notaVO.getHabitos_trabajo()[0].substring(2,  notaVO.getHabitos_trabajo()[0].length()));
                p2.put("parameter21", notaVO.getHabitos_trabajo()[1].substring(2,  notaVO.getHabitos_trabajo()[1].length()));
                p2.put("parameter22", notaVO.getHabitos_trabajo()[2].substring(2,  notaVO.getHabitos_trabajo()[2].length()));
                p2.put("parameter23", notaVO.getHabitos_trabajo()[3].substring(2,  notaVO.getHabitos_trabajo()[3].length()));
                p2.put("parameter24", notaVO.getHabitos_trabajo()[4].substring(2,  notaVO.getHabitos_trabajo()[4].length()));
                p2.put("parameter25", notaVO.getHabitos_trabajo()[5].substring(2,  notaVO.getHabitos_trabajo()[5].length()));
                p2.put("parameter26", notaVO.getHabitos_trabajo()[6].substring(2,  notaVO.getHabitos_trabajo()[6].length()));
                p2.put("parameter27", notaVO.getHabitos_trabajo()[7].substring(2,  notaVO.getHabitos_trabajo()[7].length()));
                
                JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
                JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conexion);
                JasperViewer visor = new JasperViewer(mostrarReporte, false);
                visor.setVisible(true);
            } catch (JRException ex) {
                coordinador.getLogica().mensajeError("OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex);
            }
        }
 }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
                        lblNombres5.setText("");
                txtCodigo5.setText("");
                cbxLapso1.setSelectedIndex(0);
        this.frmDatosBoletin2.setVisible(false); 
    }//GEN-LAST:event_jButton23ActionPerformed

    private void txtCodigo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigo5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo5ActionPerformed

    private void txtCodigo5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigo5KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo5KeyTyped

    private void btnBuscar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar5ActionPerformed
        if (!txtCodigo5.getText().isEmpty()) {
            id = Integer.parseInt(txtCodigo5.getText());
            AlumnoVO alumnoVO = coordinador.consultarAlumno(txtCodigo5.getText().trim());
            if (alumnoVO.getPrimer_nombre() != null) {
                //datos del alumno
                lblNombres5.setText(alumnoVO.getPrimer_nombre() + " " + alumnoVO.getSegundo_nombre() + " " + alumnoVO.getPrimer_apellido() + " " + alumnoVO.getSegundo_apellido());

                //llenar parametros a enviar
                if (!obtenerDatos2(String.valueOf(id))) {
                    coordinador.getLogica().mensajeError("No existen notas registradas para el alumno: " + lblNombres5.getText() + " para el lapso seleccionado");
                    lblNombres5.setText("");
                    txtCodigo5.setText("");
                                    cbxLapso1.setSelectedIndex(0);
                }
            } else {
                     coordinador.getLogica().mensajeError("Codigo no existe");
                                         lblNombres5.setText("");
                    txtCodigo5.setText("");
                                    cbxLapso1.setSelectedIndex(0);
            }
        }else {
            coordinador.getLogica().mensajeAdvertencia("Ingrese un codigo");
        }
    }//GEN-LAST:event_btnBuscar5ActionPerformed

    private void cbxLapso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLapso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLapso1ActionPerformed

    private void btnReportes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportes1ActionPerformed
     this.frmDatosBoletin2.setLocationRelativeTo(null);
 this.frmDatosBoletin2.setSize(290, 200);
 this.frmDatosBoletin2.setVisible(true); 
    }//GEN-LAST:event_btnReportes1ActionPerformed

  /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bntAtras;
    public javax.swing.JButton btnAsistencia;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnBuscar2;
    private javax.swing.JButton btnBuscar3;
    private javax.swing.JButton btnBuscar4;
    private javax.swing.JButton btnBuscar5;
    public javax.swing.JButton btnDocentes;
    public javax.swing.JButton btnInscripcion;
    public javax.swing.JButton btnNotas;
    public javax.swing.JButton btnPagos;
    public javax.swing.JButton btnReportes;
    public javax.swing.JButton btnReportes1;
    public javax.swing.JButton btnSeccion;
    public javax.swing.JButton btnUsuario;
    private javax.swing.JComboBox<String> cbxLapso;
    private javax.swing.JComboBox<String> cbxLapso1;
    private javax.swing.JFrame frmDatosBoletin;
    private javax.swing.JFrame frmDatosBoletin2;
    private javax.swing.JFrame frmDatosConstanciaEstudio;
    private javax.swing.JFrame frmDatosConstanciaInscripcion;
    private javax.swing.JFrame frmDatosConstanciaPago;
    private javax.swing.JFrame frmDatosNumeroCedula;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblNombres1;
    private javax.swing.JLabel lblNombres2;
    private javax.swing.JLabel lblNombres3;
    private javax.swing.JLabel lblNombres4;
    private javax.swing.JLabel lblNombres5;
    public javax.swing.JLabel lblUsuarioActvo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigo1;
    private javax.swing.JTextField txtCodigo2;
    private javax.swing.JTextField txtCodigo3;
    private javax.swing.JTextField txtCodigo4;
    private javax.swing.JTextField txtCodigo5;
    private javax.swing.JTextField txtNacimiento;
    // End of variables declaration//GEN-END:variables

    public void setCoordinador(Coordinador coordinador) {
       this.coordinador = coordinador;
    }
    
        private String consultarPago(String id) {
        /**
         * pagos consulta
         */
        PagoVO consultarPago = coordinador.getPagoDAO().consultarPago(id);
        if (consultarPago.getPago()!= null) {

            //asigno valores desde la bd a datos locales para hacer calculos

//            if(Boolean.valueOf(consultarPago.getPago()[8])){
//                return "septiembre";
//            }else if(Boolean.valueOf(consultarPago.getPago()[9])){
//                return "octubre";
//            }else if(Boolean.valueOf(consultarPago.getPago()[10])){
//                return "noviembre";
//            }else if(Boolean.valueOf(consultarPago.getPago()[11])){
//                return "diciembre";
//            }else if(Boolean.valueOf(consultarPago.getPago()[0])){
//                return "enero";
//            }else if(Boolean.valueOf(consultarPago.getPago()[1])){
//                return "febrero";
//            }else if(Boolean.valueOf(consultarPago.getPago()[2])){
//                return "marzo";
//            }else if(Boolean.valueOf(consultarPago.getPago()[3])){
//                return "abril";
//            }else if(Boolean.valueOf(consultarPago.getPago()[4])){
//                return "mayo";
//            }else if(Boolean.valueOf(consultarPago.getPago()[5])){
//                return "junio";
//            }else if(Boolean.valueOf(consultarPago.getPago()[6])){
//                return "julio";
//            }else if(Boolean.valueOf(consultarPago.getPago()[7])){
//                return "agosto";
//            }
            return "";
        }else{
            coordinador.getLogica().mensajeError("Alumno sin pagos procesados");
            lblNombres1.setText("");
            txtCodigo1.setText("");
            return "";
        }
        /**
         *
         */
    }

    private boolean obtenerDatos2(String codigo) {
                VO.NotaVO notaVO =  coordinador.getNotaDAO().consultarNotaPorLapso(codigo, (cbxLapso.getSelectedIndex()+1));
                if (notaVO.getFecha()!=null) {
                 return true;
        } else {
                 return false;
        }
    }
    
     private VO.NotaVO obtenerDatos(String codigo) {
                VO.NotaVO notaVO =  coordinador.getNotaDAO().consultarNotaPorLapso(codigo, (cbxLapso.getSelectedIndex()+1));
                
              /*  notaVO.getFormacion_personal_social()[0].substring(3,  notaVO.getFormacion_personal_social()[0].length());
               jComboBox64.setSelectedItem(notaVO.getFormacion_personal_social()[1].substring(2));
                jComboBox65.setSelectedItem(notaVO.getFormacion_personal_social()[2].substring(2));
                jComboBox66.setSelectedItem(notaVO.getFormacion_personal_social()[3].substring(2));
                jComboBox67.setSelectedItem(notaVO.getFormacion_personal_social()[4].substring(2));
                jComboBox68.setSelectedItem(notaVO.getFormacion_personal_social()[5].substring(2));
                jComboBox69.setSelectedItem(notaVO.getFormacion_personal_social()[6].substring(2));
                jComboBox70.setSelectedItem(notaVO.getFormacion_personal_social()[7].substring(2));
                jComboBox71.setSelectedItem(notaVO.getFormacion_personal_social()[8].substring(2));
                
                 jComboBox72.setSelectedItem(notaVO.getRelacion_ambiente()[0].substring(2));
                jComboBox73.setSelectedItem(notaVO.getRelacion_ambiente()[1].substring(2));
                jComboBox74.setSelectedItem(notaVO.getRelacion_ambiente()[2].substring(2));
                jComboBox75.setSelectedItem(notaVO.getRelacion_ambiente()[3].substring(2));
                jComboBox76.setSelectedItem(notaVO.getRelacion_ambiente()[4].substring(2));
                jComboBox77.setSelectedItem(notaVO.getRelacion_ambiente()[5].substring(2));
                jComboBox78.setSelectedItem(notaVO.getRelacion_ambiente()[6].substring(2));
                jComboBox79.setSelectedItem(notaVO.getRelacion_ambiente()[7].substring(2));
                 jComboBox80.setSelectedItem(notaVO.getRelacion_ambiente()[8].substring(2));
                jComboBox81.setSelectedItem(notaVO.getRelacion_ambiente()[9].substring(3));

                jComboBox91.setSelectedItem(notaVO.getComunicacion_presentacion()[0].substring(2));
                jComboBox90.setSelectedItem(notaVO.getComunicacion_presentacion()[1].substring(2));
                jComboBox89.setSelectedItem(notaVO.getComunicacion_presentacion()[2].substring(2));
                jComboBox88.setSelectedItem(notaVO.getComunicacion_presentacion()[3].substring(2));
                jComboBox87.setSelectedItem(notaVO.getComunicacion_presentacion()[4].substring(2));
                jComboBox86.setSelectedItem(notaVO.getComunicacion_presentacion()[5].substring(2));
                jComboBox85.setSelectedItem(notaVO.getComunicacion_presentacion()[6].substring(2));
                jComboBox84.setSelectedItem(notaVO.getComunicacion_presentacion()[7].substring(2));
                jComboBox83.setSelectedItem(notaVO.getComunicacion_presentacion()[8].substring(2));
                jComboBox82.setSelectedItem(notaVO.getComunicacion_presentacion()[9].substring(3));
                jComboBox92.setSelectedItem(notaVO.getComunicacion_presentacion()[10].substring(3));
                jComboBox93.setSelectedItem(notaVO.getComunicacion_presentacion()[11].substring(3));
                jComboBox94.setSelectedItem(notaVO.getComunicacion_presentacion()[12].substring(3));
                jComboBox95.setSelectedItem(notaVO.getComunicacion_presentacion()[13].substring(3));

                jComboBox96.setSelectedItem(notaVO.getHabitos_trabajo()[0].substring(2));
                jComboBox97.setSelectedItem(notaVO.getIndicadores_evaluados()[1].substring(2));
                jComboBox98.setSelectedItem(notaVO.getIndicadores_evaluados()[2].substring(2));
                jComboBox99.setSelectedItem(notaVO.getIndicadores_evaluados()[3].substring(2));
                jComboBox100.setSelectedItem(notaVO.getIndicadores_evaluados()[4].substring(2));
                jComboBox101.setSelectedItem(notaVO.getIndicadores_evaluados()[5].substring(2));
                jComboBox102.setSelectedItem(notaVO.getIndicadores_evaluados()[6].substring(2));
                jComboBox103.setSelectedItem(notaVO.getIndicadores_evaluados()[7].substring(2));
                jComboBox104.setSelectedItem(notaVO.getIndicadores_evaluados()[8].substring(2));
                jComboBox105.setSelectedItem(notaVO.getIndicadores_evaluados()[9].substring(3));
                jComboBox106.setSelectedItem(notaVO.getIndicadores_evaluados()[10].substring(3));
                jComboBox107.setSelectedItem(notaVO.getIndicadores_evaluados()[11].substring(3));
                jComboBox108.setSelectedItem(notaVO.getIndicadores_evaluados()[12].substring(3));
                jComboBox109.setSelectedItem(notaVO.getIndicadores_evaluados()[13].substring(3));
                jComboBox110.setSelectedItem(notaVO.getIndicadores_evaluados()[14].substring(3));
                jComboBox111.setSelectedItem(notaVO.getIndicadores_evaluados()[15].substring(3));
                jComboBox112.setSelectedItem(notaVO.getIndicadores_evaluados()[16].substring(3));
                jComboBox113.setSelectedItem(notaVO.getIndicadores_evaluados()[17].substring(3));
                jComboBox114.setSelectedItem(notaVO.getIndicadores_evaluados()[18].substring(3));

                jComboBox115.setSelectedItem(notaVO.getHabitos_trabajo()[0].substring(2));
                jComboBox116.setSelectedItem(notaVO.getHabitos_trabajo()[1].substring(2));
                jComboBox117.setSelectedItem(notaVO.getHabitos_trabajo()[2].substring(2));
                jComboBox118.setSelectedItem(notaVO.getHabitos_trabajo()[3].substring(2));
                jComboBox119.setSelectedItem(notaVO.getHabitos_trabajo()[4].substring(2));
                jComboBox120.setSelectedItem(notaVO.getHabitos_trabajo()[5].substring(2));
                jComboBox121.setSelectedItem(notaVO.getHabitos_trabajo()[6].substring(2));
                jComboBox122.setSelectedItem(notaVO.getHabitos_trabajo()[7].substring(2));
                jComboBox123.setSelectedItem(notaVO.getHabitos_trabajo()[8].substring(2));
                 jComboBox124.setSelectedItem(notaVO.getHabitos_trabajo()[9].substring(3));*/
                 return notaVO;
    }
}
