/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Coordinador;
import VO.AlumnoVO;
import VO.PagoVO;
import VO.RepresentanteVO;
import java.awt.Image;
import java.sql.Connection;
import java.text.ParseException;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Lenovo
 */
public class frmMenuReportes extends javax.swing.JFrame {

    private Coordinador coordinador;
    private final ImageIcon iconLogo = new javax.swing.ImageIcon(getClass().getResource("/Recursos/logo.png"));
    private String ampm;
    private String hora;
    private String minutos;
    private String segundos;
    private long i=0;
    private int id;

    /**
     * Creates new form frmMenu
     */
    public frmMenuReportes() {
        this.setlook();
         initComponents();
        setLocationRelativeTo(null);
    }
    
    public void setlook() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void ajustar(JLabel label, ImageIcon icon) {
        //esta funcion ajusta un icono(parametro) al tamaño del label (parametro)
        Icon icono = new ImageIcon(icon.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_DEFAULT));
        label.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmDatosConstanciaInscripcion = new javax.swing.JFrame();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        lblNombres = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        frmDatosConstanciaPago = new javax.swing.JFrame();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        txtCodigo1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        btnBuscar1 = new javax.swing.JButton();
        lblNombres1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblMes = new javax.swing.JLabel();
        frmDatosNumeroCedula = new javax.swing.JFrame();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        txtCodigo2 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        btnBuscar2 = new javax.swing.JButton();
        lblNombres2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNacimiento = new javax.swing.JTextField();
        frmDatosConstanciaEstudio = new javax.swing.JFrame();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        txtCodigo3 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        btnBuscar3 = new javax.swing.JButton();
        lblNombres3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bntAtras = new javax.swing.JButton();
        lblUsuarioActvo = new javax.swing.JLabel();
        btnNotas = new javax.swing.JButton();
        btnPagos = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        btnAsistencia = new javax.swing.JButton();
        btnSeccion = new javax.swing.JButton();
        btnInscripcion = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnDocentes = new javax.swing.JButton();

        frmDatosConstanciaInscripcion.setMaximumSize(new java.awt.Dimension(290, 225));
        frmDatosConstanciaInscripcion.setMinimumSize(new java.awt.Dimension(290, 225));
        frmDatosConstanciaInscripcion.setPreferredSize(new java.awt.Dimension(290, 225));
        frmDatosConstanciaInscripcion.setResizable(false);
        frmDatosConstanciaInscripcion.setSize(new java.awt.Dimension(290, 225));
        frmDatosConstanciaInscripcion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(69, 90, 100));
        jPanel7.setMaximumSize(new java.awt.Dimension(290, 120));
        jPanel7.setMinimumSize(new java.awt.Dimension(290, 120));
        jPanel7.setPreferredSize(new java.awt.Dimension(290, 120));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Datos para Reporte:");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 30));

        jButton12.setText("Aceptar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 80, -1));

        jButton13.setText("Cancelar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 80, -1));

        txtCodigo.setName("txtCodigoAlumno"); // NOI18N
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        jPanel7.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 70, 30));

        jLabel30.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Codigo alumno");
        jLabel30.setName("lbl"); // NOI18N
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 30));

        btnBuscar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icon_buscar24.png"))); // NOI18N
        btnBuscar.setName("btnBuscar"); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel7.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 30, -1));

        lblNombres.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNombres.setForeground(new java.awt.Color(255, 255, 255));
        lblNombres.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 270, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombres y apellidos");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 30));

        frmDatosConstanciaInscripcion.getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 200));

        frmDatosConstanciaPago.setMaximumSize(new java.awt.Dimension(290, 225));
        frmDatosConstanciaPago.setMinimumSize(new java.awt.Dimension(290, 225));
        frmDatosConstanciaPago.setPreferredSize(new java.awt.Dimension(290, 225));
        frmDatosConstanciaPago.setResizable(false);
        frmDatosConstanciaPago.setSize(new java.awt.Dimension(290, 225));
        frmDatosConstanciaPago.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(69, 90, 100));
        jPanel8.setMaximumSize(new java.awt.Dimension(290, 120));
        jPanel8.setMinimumSize(new java.awt.Dimension(290, 120));
        jPanel8.setPreferredSize(new java.awt.Dimension(290, 120));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Datos para Reporte:");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 30));

        jButton14.setText("Aceptar");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 80, -1));

        jButton15.setText("Cancelar");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 80, -1));

        txtCodigo1.setName("txtCodigoAlumno"); // NOI18N
        txtCodigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigo1ActionPerformed(evt);
            }
        });
        txtCodigo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigo1KeyTyped(evt);
            }
        });
        jPanel8.add(txtCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 70, 30));

        jLabel31.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Codigo alumno");
        jLabel31.setName("lbl"); // NOI18N
        jPanel8.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 30));

        btnBuscar1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnBuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icon_buscar24.png"))); // NOI18N
        btnBuscar1.setName("btnBuscar"); // NOI18N
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });
        jPanel8.add(btnBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 30, -1));

        lblNombres1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNombres1.setForeground(new java.awt.Color(255, 255, 255));
        lblNombres1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.add(lblNombres1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 200, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ultimo mes pago:");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Alumno:");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 70, 30));

        lblMes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMes.setForeground(new java.awt.Color(255, 255, 255));
        lblMes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.add(lblMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 130, 30));

        frmDatosConstanciaPago.getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 200));

        frmDatosNumeroCedula.setMaximumSize(new java.awt.Dimension(290, 225));
        frmDatosNumeroCedula.setMinimumSize(new java.awt.Dimension(290, 225));
        frmDatosNumeroCedula.setPreferredSize(new java.awt.Dimension(290, 225));
        frmDatosNumeroCedula.setResizable(false);
        frmDatosNumeroCedula.setSize(new java.awt.Dimension(290, 225));
        frmDatosNumeroCedula.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(69, 90, 100));
        jPanel9.setMaximumSize(new java.awt.Dimension(290, 120));
        jPanel9.setMinimumSize(new java.awt.Dimension(290, 120));
        jPanel9.setPreferredSize(new java.awt.Dimension(290, 120));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Datos para Reporte:");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 30));

        jButton16.setText("Aceptar");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 80, -1));

        jButton17.setText("Cancelar");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 80, -1));

        txtCodigo2.setName("txtCodigoAlumno"); // NOI18N
        txtCodigo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigo2ActionPerformed(evt);
            }
        });
        txtCodigo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigo2KeyTyped(evt);
            }
        });
        jPanel9.add(txtCodigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 70, 30));

        jLabel32.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Codigo alumno");
        jLabel32.setName("lbl"); // NOI18N
        jPanel9.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 30));

        btnBuscar2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnBuscar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icon_buscar24.png"))); // NOI18N
        btnBuscar2.setName("btnBuscar"); // NOI18N
        btnBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar2ActionPerformed(evt);
            }
        });
        jPanel9.add(btnBuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 30, -1));

        lblNombres2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNombres2.setForeground(new java.awt.Color(255, 255, 255));
        lblNombres2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.add(lblNombres2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 200, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Lugar de Nacimiento:");
        jPanel9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 150, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Alumno:");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 70, 30));

        txtNacimiento.setName("txtCodigoAlumno"); // NOI18N
        txtNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNacimientoActionPerformed(evt);
            }
        });
        txtNacimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNacimientoKeyTyped(evt);
            }
        });
        jPanel9.add(txtNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 120, 30));

        frmDatosNumeroCedula.getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 200));

        frmDatosConstanciaEstudio.setMaximumSize(new java.awt.Dimension(290, 225));
        frmDatosConstanciaEstudio.setMinimumSize(new java.awt.Dimension(290, 225));
        frmDatosConstanciaEstudio.setPreferredSize(new java.awt.Dimension(290, 225));
        frmDatosConstanciaEstudio.setResizable(false);
        frmDatosConstanciaEstudio.setSize(new java.awt.Dimension(290, 225));
        frmDatosConstanciaEstudio.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(69, 90, 100));
        jPanel10.setMaximumSize(new java.awt.Dimension(290, 120));
        jPanel10.setMinimumSize(new java.awt.Dimension(290, 120));
        jPanel10.setPreferredSize(new java.awt.Dimension(290, 120));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Datos para Reporte:");
        jPanel10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 30));

        jButton18.setText("Aceptar");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 80, -1));

        jButton19.setText("Cancelar");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 80, -1));

        txtCodigo3.setName("txtCodigoAlumno"); // NOI18N
        txtCodigo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigo3ActionPerformed(evt);
            }
        });
        txtCodigo3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigo3KeyTyped(evt);
            }
        });
        jPanel10.add(txtCodigo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 70, 30));

        jLabel33.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Codigo alumno");
        jLabel33.setName("lbl"); // NOI18N
        jPanel10.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 30));

        btnBuscar3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnBuscar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icon_buscar24.png"))); // NOI18N
        btnBuscar3.setName("btnBuscar"); // NOI18N
        btnBuscar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar3ActionPerformed(evt);
            }
        });
        jPanel10.add(btnBuscar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 30, -1));

        lblNombres3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNombres3.setForeground(new java.awt.Color(255, 255, 255));
        lblNombres3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.add(lblNombres3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 270, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nombres y apellidos");
        jPanel10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 30));

        frmDatosConstanciaEstudio.getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 200));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(69, 90, 100));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 153), new java.awt.Color(0, 51, 153)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Reportes");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 340, 110));

        bntAtras.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        bntAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/icon_exit24.png"))); // NOI18N
        bntAtras.setText("Salir");
        bntAtras.setName("bntAtras"); // NOI18N
        bntAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAtrasActionPerformed(evt);
            }
        });
        jPanel2.add(bntAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 130, 30));

        lblUsuarioActvo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblUsuarioActvo.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarioActvo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuarioActvo.setText("usuario activo");
        lblUsuarioActvo.setName("lblUsuarioActivo"); // NOI18N
        jPanel2.add(lblUsuarioActvo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 170, 30));

        btnNotas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNotas.setText("Lista de Utiles Grupo 2");
        btnNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotasActionPerformed(evt);
            }
        });
        jPanel2.add(btnNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 160, 70));

        btnPagos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnPagos.setText("Constancia de Estudio");
        btnPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagosActionPerformed(evt);
            }
        });
        jPanel2.add(btnPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 160, 70));

        btnUsuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnUsuario.setText("Lista de Utiles Grupo 1");
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(btnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 160, 70));

        btnAsistencia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAsistencia.setText("Solvencia de Pago");
        btnAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsistenciaActionPerformed(evt);
            }
        });
        jPanel2.add(btnAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 160, 70));

        btnSeccion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSeccion.setText("Lista de Utiles Grupo 3");
        btnSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeccionActionPerformed(evt);
            }
        });
        jPanel2.add(btnSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 160, 70));

        btnInscripcion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnInscripcion.setText("Constancia de Inscripcion");
        btnInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscripcionActionPerformed(evt);
            }
        });
        jPanel2.add(btnInscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 180, 70));

        btnReportes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnReportes.setText("Boletin Informativo");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        jPanel2.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 160, 70));

        btnDocentes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnDocentes.setText("Numero Cedula Escolar");
        btnDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocentesActionPerformed(evt);
            }
        });
        jPanel2.add(btnDocentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 180, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 370));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsistenciaActionPerformed
 this.frmDatosConstanciaPago.setLocationRelativeTo(null);
 this.frmDatosConstanciaPago.setSize(290, 200);
 this.frmDatosConstanciaPago.setVisible(true);   
    }//GEN-LAST:event_btnAsistenciaActionPerformed

    private void btnSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeccionActionPerformed
    try {
        Connection conexion= null;
        Conexion.ConexionBd conexiondb = new Conexion.ConexionBd();
        conexion = conexiondb.getConnection();
            String dir = coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte()+ "\\lista3grupo.jrxml";
            Map<String, Object> p2 = new HashMap<>();
            p2.put("ruta", coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte());
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conexion);
            JasperViewer visor = new JasperViewer(mostrarReporte, false);
            visor.setVisible(true);
        } catch (JRException ex) {
            coordinador.getLogica().mensajeError("OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex);
    } 
    }//GEN-LAST:event_btnSeccionActionPerformed

    private void btnInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscripcionActionPerformed
 this.frmDatosConstanciaInscripcion.setLocationRelativeTo(null);
 this.frmDatosConstanciaInscripcion.setSize(290, 200);
 this.frmDatosConstanciaInscripcion.setVisible(true); 
    }//GEN-LAST:event_btnInscripcionActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed

    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
    try {
        Connection conexion= null;
        Conexion.ConexionBd conexiondb = new Conexion.ConexionBd();
        conexion = conexiondb.getConnection();
            String dir = coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte()+ "\\lista1ergrupo.jrxml";
            Map<String, Object> p2 = new HashMap<>();
            p2.put("ruta", coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte());
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conexion);
            JasperViewer visor = new JasperViewer(mostrarReporte, false);
            visor.setVisible(true);
        } catch (JRException ex) {
            coordinador.getLogica().mensajeError("OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex);
    }   
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagosActionPerformed
 this.frmDatosConstanciaEstudio.setLocationRelativeTo(null);
 this.frmDatosConstanciaEstudio.setSize(290, 200);
 this.frmDatosConstanciaEstudio.setVisible(true); 
    }//GEN-LAST:event_btnPagosActionPerformed

    private void bntAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAtrasActionPerformed
    this.dispose();
    }//GEN-LAST:event_bntAtrasActionPerformed

    private void btnDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocentesActionPerformed
 this.frmDatosNumeroCedula.setLocationRelativeTo(null);
 this.frmDatosNumeroCedula.setSize(290, 200);
 this.frmDatosNumeroCedula.setVisible(true); 
    }//GEN-LAST:event_btnDocentesActionPerformed

    private void btnNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotasActionPerformed
    try {
        Connection conexion= null;
        Conexion.ConexionBd conexiondb = new Conexion.ConexionBd();
        conexion = conexiondb.getConnection();
            String dir = coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte()+ "\\lista2dogrupo.jrxml";
            Map<String, Object> p2 = new HashMap<>();
            p2.put("ruta", coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte());
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conexion);
            JasperViewer visor = new JasperViewer(mostrarReporte, false);
            visor.setVisible(true);
        } catch (JRException ex) {
            coordinador.getLogica().mensajeError("OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex);
    } 
    }//GEN-LAST:event_btnNotasActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        if (!lblNombres.getText().equals("")) {
            try {
                Connection conexion = null;
                Conexion.ConexionBd conexiondb = new Conexion.ConexionBd();
                conexion = conexiondb.getConnection();
                String dir = coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte() + "\\Constancia de Inscripcion.jrxml";
                double valorMatricula = 0 ;
                valorMatricula = (coordinador.getVariablesDAO().consultarVariables().getPrecio_cuota() + (coordinador.getVariablesDAO().consultarVariables().getPrecio_cuota() * coordinador.getVariablesDAO().consultarVariables().getIva()/ 100)) * 12;
                
                Map<String, Object> p2 = new HashMap<>();
                p2.put("id", id);
                p2.put("ruta", coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte());
                p2.put("matricula", valorMatricula);;
                p2.put("total", (valorMatricula+coordinador.getVariablesDAO().consultarVariables().getSeguro()));
                p2.put("anio_anterior", coordinador.getVariablesDAO().consultarVariables().getPeriodo_actual().substring(0, 4));
                p2.put("anio_siguiente", coordinador.getVariablesDAO().consultarVariables().getPeriodo_actual().substring(5, 9));
                JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
                JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conexion);
                JasperViewer visor = new JasperViewer(mostrarReporte, false);
                visor.setVisible(true);
                lblNombres.setText("");
                txtCodigo.setText("");
            } catch (JRException ex) {
                coordinador.getLogica().mensajeError("OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex);
                this.dispose();
            }
           
        }else{
               coordinador.getLogica().mensajeError("Por favor consulte un alumno");
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
                        lblNombres.setText("");
                txtCodigo.setText("");
        this.frmDatosConstanciaInscripcion.setVisible(false); 
    }//GEN-LAST:event_jButton13ActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped

    }//GEN-LAST:event_txtCodigoKeyTyped

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (!txtCodigo.getText().isEmpty()) {
            id = Integer.parseInt(txtCodigo.getText());
            AlumnoVO alumnoVO = coordinador.consultarAlumno(txtCodigo.getText().trim());
            if (alumnoVO.getPrimer_nombre() != null) {
                //datos del alumno
                lblNombres.setText(alumnoVO.getPrimer_nombre()+" "+alumnoVO.getSegundo_nombre()+" "+alumnoVO.getPrimer_apellido()+" "+alumnoVO.getSegundo_apellido());
              } else{
                     coordinador.getLogica().mensajeError("Codigo no existe");
            }
        }else {
            coordinador.getLogica().mensajeAdvertencia("Ingrese un codigo");
        }
       
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        if (!lblNombres1.getText().equals("")) {
            try {
                Connection conexion = null;
                Conexion.ConexionBd conexiondb = new Conexion.ConexionBd();
                conexion = conexiondb.getConnection();
                String dir = coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte() + "\\solvenciaPago.jrxml";

                Map<String, Object> p2 = new HashMap<>();
                p2.put("id", id);
                p2.put("ruta", coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte());
                p2.put("mes", lblMes.getText());
                JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
                JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conexion);
                JasperViewer visor = new JasperViewer(mostrarReporte, false);
                visor.setVisible(true);
                lblNombres1.setText("");
                txtCodigo1.setText("");
                lblMes.setText("");
            } catch (JRException ex) {
                coordinador.getLogica().mensajeError("OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex);
                this.dispose();
            }
           
        }else{
               coordinador.getLogica().mensajeError("Por favor consulte un alumno");
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
                        lblNombres1.setText("");
                txtCodigo1.setText("");
                lblMes.setText("");
        this.frmDatosConstanciaPago.setVisible(false);        
    }//GEN-LAST:event_jButton15ActionPerformed

    private void txtCodigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo1ActionPerformed

    private void txtCodigo1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigo1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo1KeyTyped

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        if (!txtCodigo1.getText().isEmpty()) {
            id = Integer.parseInt(txtCodigo1.getText());
            AlumnoVO alumnoVO = coordinador.consultarAlumno(txtCodigo1.getText().trim());
            if (alumnoVO.getPrimer_nombre() != null) {
                //datos del alumno
                lblNombres1.setText(alumnoVO.getPrimer_nombre()+" "+alumnoVO.getSegundo_nombre()+" "+alumnoVO.getPrimer_apellido()+" "+alumnoVO.getSegundo_apellido());
                String consultarPago = consultarPago(String.valueOf(id));
                lblMes.setText(consultarPago);
            } else{
                     coordinador.getLogica().mensajeError("Codigo no existe");
            }
        }else {
            coordinador.getLogica().mensajeAdvertencia("Ingrese un codigo");
        }
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        if (!lblNombres2.getText().equals("")) {
            if (!txtNacimiento.getText().equals("")) {
            try {
                Connection conexion = null;
                Conexion.ConexionBd conexiondb = new Conexion.ConexionBd();
                conexion = conexiondb.getConnection();
                String dir = coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte() + "\\numerocudelaescolar.jrxml";

                Map<String, Object> p2 = new HashMap<>();
                p2.put("id", id);
                p2.put("lugar", txtNacimiento.getText());
                JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
                JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conexion);
                JasperViewer visor = new JasperViewer(mostrarReporte, false);
                visor.setVisible(true);
                lblNombres2.setText("");
                txtCodigo2.setText("");
                txtNacimiento.setText("");
            } catch (JRException ex) {
                coordinador.getLogica().mensajeError("OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex);
                this.dispose();
            }
           }else{
               coordinador.getLogica().mensajeError("Por favor ingrese el lugar de nacimiento");
        }
        }else{
               coordinador.getLogica().mensajeError("Por favor consulte un alumno");
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
                        lblNombres2.setText("");
                txtCodigo2.setText("");
                txtNacimiento.setText("");
        this.frmDatosNumeroCedula.setVisible(false);     
    }//GEN-LAST:event_jButton17ActionPerformed

    private void txtCodigo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo2ActionPerformed

    private void txtCodigo2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigo2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo2KeyTyped

    private void btnBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar2ActionPerformed
        if (!txtCodigo2.getText().isEmpty()) {
            id = Integer.parseInt(txtCodigo2.getText());
            AlumnoVO alumnoVO = coordinador.consultarAlumno(txtCodigo2.getText().trim());
            if (alumnoVO.getPrimer_nombre() != null) {
                //datos del alumno
                lblNombres2.setText(alumnoVO.getPrimer_nombre()+" "+alumnoVO.getSegundo_nombre()+" "+alumnoVO.getPrimer_apellido()+" "+alumnoVO.getSegundo_apellido());
              } else{
                     coordinador.getLogica().mensajeError("Codigo no existe");
            }
        }else {
            coordinador.getLogica().mensajeAdvertencia("Ingrese un codigo");
        }
    }//GEN-LAST:event_btnBuscar2ActionPerformed

    private void txtNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNacimientoActionPerformed

    private void txtNacimientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNacimientoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNacimientoKeyTyped

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        if (!lblNombres3.getText().equals("")) {
            try {
                Connection conexion = null;
                Conexion.ConexionBd conexiondb = new Conexion.ConexionBd();
                conexion = conexiondb.getConnection();
                String dir = coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte() + "\\constancia.jrxml";
          
                Map<String, Object> p2 = new HashMap<>();
                p2.put("id", id);
                p2.put("ruta", coordinador.getVariablesDAO().consultarVariables().getUbicacion_reporte());
                JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
                JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, p2, conexion);
                JasperViewer visor = new JasperViewer(mostrarReporte, false);
                visor.setVisible(true);
                lblNombres3.setText("");
                txtCodigo3.setText("");
            } catch (JRException ex) {
                coordinador.getLogica().mensajeError("OCURRIO UN ERROR AL CARGAR EL REPORTE.\n" + ex);
                this.dispose();
            }
           
        }else{
               coordinador.getLogica().mensajeError("Por favor consulte un alumno");
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
                        lblNombres3.setText("");
                txtCodigo3.setText("");
        this.frmDatosConstanciaEstudio.setVisible(false); 
    }//GEN-LAST:event_jButton19ActionPerformed

    private void txtCodigo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo3ActionPerformed

    private void txtCodigo3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigo3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo3KeyTyped

    private void btnBuscar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar3ActionPerformed
        if (!txtCodigo3.getText().isEmpty()) {
            id = Integer.parseInt(txtCodigo3.getText());
            AlumnoVO alumnoVO = coordinador.consultarAlumno(txtCodigo3.getText().trim());
            if (alumnoVO.getPrimer_nombre() != null) {
                //datos del alumno
                lblNombres3.setText(alumnoVO.getPrimer_nombre()+" "+alumnoVO.getSegundo_nombre()+" "+alumnoVO.getPrimer_apellido()+" "+alumnoVO.getSegundo_apellido());
              } else{
                     coordinador.getLogica().mensajeError("Codigo no existe");
            }
        }else {
            coordinador.getLogica().mensajeAdvertencia("Ingrese un codigo");
        }
    }//GEN-LAST:event_btnBuscar3ActionPerformed

  /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bntAtras;
    public javax.swing.JButton btnAsistencia;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnBuscar2;
    private javax.swing.JButton btnBuscar3;
    public javax.swing.JButton btnDocentes;
    public javax.swing.JButton btnInscripcion;
    public javax.swing.JButton btnNotas;
    public javax.swing.JButton btnPagos;
    public javax.swing.JButton btnReportes;
    public javax.swing.JButton btnSeccion;
    public javax.swing.JButton btnUsuario;
    private javax.swing.JFrame frmDatosConstanciaEstudio;
    private javax.swing.JFrame frmDatosConstanciaInscripcion;
    private javax.swing.JFrame frmDatosConstanciaPago;
    private javax.swing.JFrame frmDatosNumeroCedula;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblNombres1;
    private javax.swing.JLabel lblNombres2;
    private javax.swing.JLabel lblNombres3;
    public javax.swing.JLabel lblUsuarioActvo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigo1;
    private javax.swing.JTextField txtCodigo2;
    private javax.swing.JTextField txtCodigo3;
    private javax.swing.JTextField txtNacimiento;
    // End of variables declaration//GEN-END:variables

    public void setCoordinador(Coordinador coordinador) {
       this.coordinador = coordinador;
    }
    
        private String consultarPago(String id) {
        /**
         * pagos consulta
         */
        PagoVO consultarPago = coordinador.getPagoDAO().consultarPago(id);
        if (consultarPago.getCuotas() != null) {

            //asigno valores desde la bd a datos locales para hacer calculos

            if(Boolean.valueOf(consultarPago.getCuotas()[8])){
                return "septiembre";
            }else if(Boolean.valueOf(consultarPago.getCuotas()[9])){
                return "octubre";
            }else if(Boolean.valueOf(consultarPago.getCuotas()[10])){
                return "noviembre";
            }else if(Boolean.valueOf(consultarPago.getCuotas()[11])){
                return "diciembre";
            }else if(Boolean.valueOf(consultarPago.getCuotas()[0])){
                return "enero";
            }else if(Boolean.valueOf(consultarPago.getCuotas()[1])){
                return "febrero";
            }else if(Boolean.valueOf(consultarPago.getCuotas()[2])){
                return "marzo";
            }else if(Boolean.valueOf(consultarPago.getCuotas()[3])){
                return "abril";
            }else if(Boolean.valueOf(consultarPago.getCuotas()[4])){
                return "mayo";
            }else if(Boolean.valueOf(consultarPago.getCuotas()[5])){
                return "junio";
            }else if(Boolean.valueOf(consultarPago.getCuotas()[6])){
                return "julio";
            }else if(Boolean.valueOf(consultarPago.getCuotas()[7])){
                return "agosto";
            }
            return "";
        }else{
            coordinador.getLogica().mensajeError("Alumno sin pagos procesados");
            lblNombres1.setText("");
            txtCodigo1.setText("");
            return "";
        }
        /**
         *
         */
    }
}
